//+------------------------------------------------------------------+
//| VaultTrades EMA20 Automation EA                                  |
//| TradingView -> VaultTrades -> MT5                                |
//+------------------------------------------------------------------+
#property strict
#property version   "4.00"
#property description "Dedicated VaultTrades EMA20 bridge. Only Key Code and Enable Live Execution are configurable."

#include <Trade/Trade.mqh>

CTrade trade;

//==================================================================
// PRODUCTION CONFIGURATION — DO NOT CHANGE IN MT5
//==================================================================
const string VAULTTRADES_URL = "https://vaulttradesve.com/api/execution/tradingview";
const string EMA20_STRATEGY_ID = "ema20-pullback-morning-engine";
// This is the fixed EMA20 strategy identifier. It is compiled into the EA.
// The per-trade signal_id is generated by TradingView and is never a manual MT5 input.
const string STRATEGY_ID       = EMA20_STRATEGY_ID;
const string TV_SYMBOL       = "XAUUSD";

// Broker symbol resolution is automatic.
// The EA tries exact XAUUSD first, then broker suffix/prefix variants,
// then common GOLD aliases. No manual symbol mapping is required.
const double LOT_SIZE        = 0.01;
const int    POLL_SECONDS    = 2;
const int    DEVIATION_PTS  = 50;
const long   MAGIC_NUMBER   = 20260922;

//==================================================================
// ONLY TWO MT5 CONTROLS
//==================================================================

// Enter the VaultTrades webhook key code supplied for this EA.
input string InpKeyCode = "";

// OFF = OBSERVE: receive/log signals, never place an order.
// ON  = LIVE: receive and execute eligible EMA20 signals.
input bool   InpEnableLiveExecution = false;

//==================================================================
// Runtime state
//==================================================================
string   g_lastSignalId = "";
datetime g_lastPoll     = 0;
string   g_brokerSymbol = "";

//==================================================================
// JSON helpers
//==================================================================
string JsonString(const string json,const string key)
{
   string needle = "\"" + key + "\":";
   int p = StringFind(json,needle);

   if(p < 0)
      return "";

   p += StringLen(needle);

   while(p < StringLen(json))
   {
      ushort c = StringGetCharacter(json,p);

      if(c != ' ' && c != '\t' && c != '\r' && c != '\n')
         break;

      p++;
   }

   if(p >= StringLen(json) || StringGetCharacter(json,p) != '\"')
      return "";

   p++;

   int e = p;

   while(e < StringLen(json))
   {
      ushort c = StringGetCharacter(json,e);

      if(c == '\"' && (e == p || StringGetCharacter(json,e - 1) != '\\'))
         break;

      e++;
   }

   if(e >= StringLen(json))
      return "";

   return StringSubstr(json,p,e - p);
}

double JsonNumber(const string json,const string key)
{
   string needle = "\"" + key + "\":";
   int p = StringFind(json,needle);

   if(p < 0)
      return 0.0;

   p += StringLen(needle);

   while(p < StringLen(json))
   {
      ushort c = StringGetCharacter(json,p);

      if(c != ' ' && c != '\t' && c != '\r' && c != '\n')
         break;

      p++;
   }

   int e = p;

   while(e < StringLen(json))
   {
      ushort c = StringGetCharacter(json,e);

      if((c >= '0' && c <= '9') ||
         c == '-' || c == '+' || c == '.' ||
         c == 'e' || c == 'E')
      {
         e++;
      }
      else
      {
         break;
      }
   }

   if(e <= p)
      return 0.0;

   return StringToDouble(StringSubstr(json,p,e - p));
}

//==================================================================
// Extract the first complete JSON object from an API response.
// Handles nested objects and quoted braces.
//==================================================================
string ExtractFirstObject(const string json)
{
   int start = StringFind(json,"{");

   if(start < 0)
      return "";

   int depth = 0;
   bool inString = false;
   bool escaped = false;

   for(int i = start; i < StringLen(json); i++)
   {
      ushort c = StringGetCharacter(json,i);

      if(inString)
      {
         if(escaped)
         {
            escaped = false;
            continue;
         }

         if(c == '\\')
         {
            escaped = true;
            continue;
         }

         if(c == '\"')
            inString = false;

         continue;
      }

      if(c == '\"')
      {
         inString = true;
         continue;
      }

      if(c == '{')
      {
         depth++;
      }
      else if(c == '}')
      {
         depth--;

         if(depth == 0)
            return StringSubstr(json,start,i - start + 1);
      }
   }

   return "";
}

//==================================================================
// Broker symbol resolver
//==================================================================
bool IsUsableSymbol(const string symbol)
{
   if(symbol == "")
      return false;

   long tradeMode = SymbolInfoInteger(symbol,SYMBOL_TRADE_MODE);

   if(tradeMode == SYMBOL_TRADE_MODE_DISABLED)
      return false;

   return SymbolSelect(symbol,true);
}

string FindSymbolStartingWith(const string base)
{
   string upperBase = base;
   StringToUpper(upperBase);

   // First search visible symbols.
   int total = SymbolsTotal(false);

   for(int i = 0; i < total; i++)
   {
      string candidate = SymbolName(i,false);
      string upperCandidate = candidate;
      StringToUpper(upperCandidate);

      if(StringFind(upperCandidate,upperBase) == 0 &&
         IsUsableSymbol(candidate))
      {
         return candidate;
      }
   }

   // Then search all broker symbols, including hidden Market Watch symbols.
   total = SymbolsTotal(true);

   for(int j = 0; j < total; j++)
   {
      string candidate2 = SymbolName(j,true);
      string upperCandidate2 = candidate2;
      StringToUpper(upperCandidate2);

      if(StringFind(upperCandidate2,upperBase) == 0 &&
         IsUsableSymbol(candidate2))
      {
         return candidate2;
      }
   }

   return "";
}

string FindSymbolContaining(const string base)
{
   string upperBase = base;
   StringToUpper(upperBase);

   int total = SymbolsTotal(true);

   for(int i = 0; i < total; i++)
   {
      string candidate = SymbolName(i,true);
      string upperCandidate = candidate;
      StringToUpper(upperCandidate);

      if(StringFind(upperCandidate,upperBase) >= 0 &&
         IsUsableSymbol(candidate))
      {
         return candidate;
      }
   }

   return "";
}

string ResolveXAUUSDSymbol()
{
   // 1. Exact canonical symbol.
   if(IsUsableSymbol(TV_SYMBOL))
      return TV_SYMBOL;

   // 2. Standard broker suffix variants: XAUUSDm, XAUUSD.a, XAUUSDpro, etc.
   string resolved = FindSymbolStartingWith(TV_SYMBOL);

   if(resolved != "")
      return resolved;

   // 3. Common broker gold aliases.
   string aliases[6] =
   {
      "GOLD",
      "GOLDm",
      "GOLD.a",
      "GOLDpro",
      "XAUUSD.",
      "XAUUSD-"
   };

   for(int i = 0; i < ArraySize(aliases); i++)
   {
      if(IsUsableSymbol(aliases[i]))
         return aliases[i];
   }

   // 4. Last-resort containing search.
   resolved = FindSymbolContaining("XAUUSD");

   if(resolved != "")
      return resolved;

   resolved = FindSymbolContaining("GOLD");

   return resolved;
}

//==================================================================
// Current EA execution mode
//==================================================================
string CurrentMode()
{
   return InpEnableLiveExecution ? "LIVE" : "OBSERVE";
}

//==================================================================
// Poll VaultTrades
//==================================================================
string PollVaultTrades()
{
   string mode = CurrentMode();

   string url =
      VAULTTRADES_URL +
      "?strategy_id=" + STRATEGY_ID +
      "&symbol=" + TV_SYMBOL +
      "&execution_mode=" + mode;

   string headers =
      "Accept: application/json\r\n" +
      "X-VaultTrades-Webhook-Secret: " + InpKeyCode + "\r\n";

   char data[];
   char result[];
   string resultHeaders;

   ResetLastError();

   int status = WebRequest(
      "GET",
      url,
      headers,
      5000,
      data,
      result,
      resultHeaders
   );

   if(status == -1)
   {
      Print(
         "VaultTrades WebRequest error=",
         GetLastError(),
         ". Add https://vaulttradesve.com in MT5: ",
         "Tools > Options > Expert Advisors > Allow WebRequest."
      );

      return "";
   }

   if(status != 200)
   {
      Print(
         "VaultTrades HTTP=",
         status,
         " response=",
         CharArrayToString(result)
      );

      return "";
   }

   return CharArrayToString(result);
}

//==================================================================
// Send MT5 acknowledgement to VaultTrades
//==================================================================
bool PostAck(const string signalId,const ulong ticket)
{
   if(InpKeyCode == "" || signalId == "")
      return false;

   string headers =
      "Content-Type: application/json\r\n" +
      "X-VaultTrades-Webhook-Secret: " + InpKeyCode + "\r\n";

   string body =
      "{"
      "\"signal_id\":\"" + signalId + "\","
      "\"event\":\"MT5_ACK\","
      "\"ticket\":" + IntegerToString((long)ticket) + ","
      "\"source\":\"MT5\","
      "\"strategy_id\":\"" + STRATEGY_ID + "\""
      "}";

   char data[];
   char result[];
   string resultHeaders;

   StringToCharArray(body,data,0,-1,CP_UTF8);

   ResetLastError();

   int status = WebRequest(
      "POST",
      VAULTTRADES_URL,
      headers,
      5000,
      data,
      result,
      resultHeaders
   );

   if(status != 200)
   {
      Print(
         "VaultTrades ACK failed. HTTP=",
         status,
         " response=",
         CharArrayToString(result)
      );

      return false;
   }

   Print(
      "VaultTrades MT5 ACK sent. signal_id=",
      signalId,
      " ticket=",
      ticket
   );

   return true;
}

//==================================================================
// Process one EMA20 signal
//==================================================================
bool ProcessSignal(const string signal)
{
   string signalId    = JsonString(signal,"signal_id");
   string direction   = JsonString(signal,"direction");
   string sourceSymbol= JsonString(signal,"symbol");
   string mode        = JsonString(signal,"execution_mode");
   string strategyId  = JsonString(signal,"strategy_id");

   double entry = JsonNumber(signal,"entry_price");
   double sl    = JsonNumber(signal,"stop_loss");
   double tp    = JsonNumber(signal,"tp1");

   if(signalId == "")
   {
      Print("VaultTrades EMA20: signal_id missing.");
      return false;
   }

   // This EA is dedicated to EMA20 only.
   if(strategyId != "" && strategyId != STRATEGY_ID)
   {
      Print(
         "VaultTrades EMA20: ignored non-EMA20 strategy. strategy_id=",
         strategyId
      );
      return false;
   }

   if(signalId == g_lastSignalId)
      return false;

   string expectedMode = CurrentMode();

   if(mode != expectedMode)
   {
      Print(
         "VaultTrades EMA20: mode mismatch. EA=",
         expectedMode,
         " signal=",
         mode,
         " signal_id=",
         signalId
      );
      return false;
   }

   if(g_brokerSymbol == "")
      g_brokerSymbol = ResolveXAUUSDSymbol();

   if(g_brokerSymbol == "")
   {
      Print(
         "VaultTrades EMA20: XAUUSD broker symbol could not be resolved."
      );
      return false;
   }

   // OBSERVE: receive the real signal and display it in Experts/Journal.
   // No order is sent.
   if(expectedMode == "OBSERVE")
   {
      Print(
         "VAULTTRADES EMA20 OBSERVE | signal_id=",
         signalId,
         " | direction=",
         direction,
         " | TV=",
         sourceSymbol,
         " | MT5=",
         g_brokerSymbol,
         " | entry=",
         DoubleToString(entry,5),
         " | SL=",
         DoubleToString(sl,5),
         " | TP1=",
         DoubleToString(tp,5)
      );

      g_lastSignalId = signalId;
      return true;
   }

   // LIVE validation.
   if(direction != "BUY" && direction != "SELL")
   {
      Print(
         "VaultTrades EMA20 LIVE: invalid direction=",
         direction,
         " signal_id=",
         signalId
      );
      return false;
   }

   if(entry <= 0.0 || sl <= 0.0 || tp <= 0.0)
   {
      Print(
         "VaultTrades EMA20 LIVE: invalid prices. signal_id=",
         signalId,
         " entry=",
         entry,
         " SL=",
         sl,
         " TP1=",
         tp
      );
      return false;
   }

   trade.SetExpertMagicNumber(MAGIC_NUMBER);
   trade.SetDeviationInPoints(DEVIATION_PTS);
   trade.SetTypeFillingBySymbol(g_brokerSymbol);

   bool ok = false;

   if(direction == "BUY")
   {
      ok = trade.Buy(
         LOT_SIZE,
         g_brokerSymbol,
         0.0,
         sl,
         tp,
         "VaultTrades EMA20 " + signalId
      );
   }
   else
   {
      ok = trade.Sell(
         LOT_SIZE,
         g_brokerSymbol,
         0.0,
         sl,
         tp,
         "VaultTrades EMA20 " + signalId
      );
   }

   if(!ok)
   {
      Print(
         "VaultTrades EMA20 LIVE order failed. signal_id=",
         signalId,
         " retcode=",
         trade.ResultRetcode(),
         " description=",
         trade.ResultRetcodeDescription()
      );

      return false;
   }

   ulong ticket = trade.ResultOrder();

   g_lastSignalId = signalId;

   PostAck(signalId,ticket);

   Print(
      "VAULTTRADES EMA20 LIVE EXECUTED | signal_id=",
      signalId,
      " | direction=",
      direction,
      " | MT5=",
      g_brokerSymbol,
      " | ticket=",
      ticket
   );

   return true;
}

//==================================================================
// Extract the actual signal object from the VaultTrades API wrapper.
//
// Production GET responses are shaped like:
// {"ok":true,"status":"SIGNAL_READY","signals":[{"signal_id":"...",...}]}
// The previous parser extracted the OUTER wrapper and therefore logged
// "signal_id missing" even when the nested signal contained the ID.
//==================================================================
string ExtractSignalObject(const string json)
{
   int searchFrom = 0;

   while(searchFrom < StringLen(json))
   {
      int objectStart = StringFind(json,"{",searchFrom);

      if(objectStart < 0)
         break;

      string candidate = ExtractFirstObject(StringSubstr(json,objectStart));

      if(candidate == "")
         break;

      if(JsonString(candidate,"signal_id") != "")
         return candidate;

      searchFrom = objectStart + 1;
   }

   return "";
}

//==================================================================
// Poll and extract signal object
//==================================================================
void PollSignal()
{
   string response = PollVaultTrades();

   if(response == "")
      return;

   string signal = ExtractSignalObject(response);

   if(signal == "")
   {
      string status = JsonString(response,"status");

      if(status == "WAITING")
         return;

      Print("VaultTrades EMA20: no signal object with signal_id found in response.");
      return;
   }

   ProcessSignal(signal);
}

//==================================================================
// Initialization
//==================================================================
int OnInit()
{
   if(InpKeyCode == "")
   {
      Print(
         "VaultTrades EMA20 EA: Key Code is required. ",
         "Enter the VaultTrades webhook key code in the single Key Code field."
      );
   }

   g_brokerSymbol = ResolveXAUUSDSymbol();

   Print("============================================================");
   Print("VaultTrades EMA20 Automation EA");
   Print("COMPILED EMA20 STRATEGY ID: ",EMA20_STRATEGY_ID);
   Print("Endpoint: ",VAULTTRADES_URL);
   Print("TradingView symbol: ",TV_SYMBOL);
   Print("Resolved MT5 symbol: ",g_brokerSymbol);
   Print("Mode: ",CurrentMode());
   Print("Live execution: ",InpEnableLiveExecution ? "ENABLED" : "OBSERVE");
   Print("============================================================");

   if(g_brokerSymbol == "")
   {
      Print(
         "VaultTrades EMA20 EA WARNING: no usable XAUUSD/GOLD symbol found."
      );
   }

   EventSetTimer(MathMax(1,POLL_SECONDS));

   return INIT_SUCCEEDED;
}

//==================================================================
// Deinitialization
//==================================================================
void OnDeinit(const int reason)
{
   EventKillTimer();

   Print(
      "VaultTrades EMA20 Automation EA stopped. reason=",
      reason
   );
}

//==================================================================
// Timer
//==================================================================
void OnTimer()
{
   if((TimeCurrent() - g_lastPoll) < POLL_SECONDS)
      return;

   g_lastPoll = TimeCurrent();

   PollSignal();
}
//+------------------------------------------------------------------+
