"use client";
import { useEffect, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";

const days=[
 [1,"Day 1","https://docs.google.com/presentation/d/1qRzJK9ZBEcro-A5tpGrgJ_sqazSeIvTh/edit?usp=drive_link&ouid=107858755837339377719&rtpof=true&sd=true"],
 [2,"Day 2","https://docs.google.com/presentation/d/1Kn679ll-2-3QyQo39PyTC5cCidbgwg_R/edit?usp=drive_link&ouid=107858755837339377719&rtpof=true&sd=true"],
 [3,"Day 3","https://docs.google.com/presentation/d/1-dEDPeRd06nihxCf_o3axBpjV27j6YdJ/edit?usp=drive_link&ouid=107858755837339377719&rtpof=true&sd=true"],
 [4,"Day 4","https://docs.google.com/presentation/d/1Doxy-jLhlGFyHQUOyPVgbDVUE5AzHiNz/edit?usp=drive_link&ouid=107858755837339377719&rtpof=true&sd=true"],
 [5,"Day 5","https://docs.google.com/presentation/d/14AhsRXnSJ7E84wAA1CX9RL4Tjy_KFoAS/edit?usp=drive_link&ouid=107858755837339377719&rtpof=true&sd=true"]
];
export default function Mentorship(){const [allowed,setAllowed]=useState(false);const [progress,setProgress]=useState<Record<number,boolean>>({});useEffect(()=>{(async()=>{const sb=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data:a}=await sb.auth.getUser();if(!a.user)return;const {data:u}=await sb.from("users").select("id,mentorship_enrolled").eq("auth_user_id",a.user.id).single();if(!u?.mentorship_enrolled)return;setAllowed(true);const {data:p}=await sb.from("mentorship_progress").select("day,completed").eq("user_id",u.id);setProgress(Object.fromEntries((p??[]).map((x:any)=>[x.day,x.completed])));})();},[]);if(!allowed)return <main className="shell"><section className="card"><div className="section-label">FOUNDERS MENTORSHIP</div><h1 className="title">Access Locked</h1><p className="muted">Your account is not enrolled in the Founders 30 Days Mentorship Program.</p></section></main>;return <main className="shell"><section className="card"><div className="section-label">FOUNDERS MENTORSHIP</div><h1 className="title">30 Days Founders Mentorship Program</h1><p className="muted">Approximately 1 hour per day. Complete each session in full before marking the day complete. Days 6–30 will be added as they become available.</p><div style={{display:"grid",gap:12,marginTop:20}}>{days.map(([day,title,url])=><article className="condition-box" key={day}><strong>{title} · 1 hour</strong><p className="muted">{progress[day as number]?"Completed":"Not completed"}</p><a className="button" href={url as string} target="_blank" rel="noreferrer">Open recorded session</a></article>)}</div></section></main>}
