import type { StrategyRuleSet } from "./types";

/** EMA20 Pullback Morning Engine — authoritative strategy contract. */
export const ema20Rules: StrategyRuleSet = {
  id: "ema20",
  name: "EMA20 Pullback Morning Engine",
  description: "Structure → EMA20 touch → rejection → break → UT Bot OR SMI confirmation → entry.",
  source: "PINE_SCRIPT",
  timeframes: ["chart timeframe"],
  sequence: ["Bullish/Bearish structure", "EMA20 touch", "Rejection", "Rejection active", "Break of stored rejection level", "UT Bot OR SMI confirmation", "New signal transition", "ENTRY"],
  mandatoryRules: [
    "EMA20 length 20; EMA105 length 105 is context only.",
    "ATR length 14; EMA20 touch tolerance is 0.20 × ATR.",
    "Confirmed pivot high/low structure uses pivot length 3 with Pine pivot confirmation delay.",
    "Bullish structure requires (HH OR HL) AND EMA20 rising AND close > EMA20.",
    "Bearish structure requires (LH OR LL) AND EMA20 falling AND close < EMA20.",
    "Bullish touch requires low <= EMA20 + tolerance AND low >= EMA20 - tolerance.",
    "Bearish touch requires high >= EMA20 - tolerance AND high <= EMA20 + tolerance.",
    "Bullish rejection requires bullish structure + bullish touch + close > open + close > EMA20.",
    "Bearish rejection requires bearish structure + bearish touch + close < open + close < EMA20.",
    "A rejection stores its high, low and bar index as persistent setup state.",
    "A stored rejection is active only on subsequent bars through confirmationBars (default 3).",
    "Bullish rejection is invalidated when close < stored bullish rejection low.",
    "Bearish rejection is invalidated when close > stored bearish rejection high.",
    "Bullish trigger is an active close above stored bullish rejection high.",
    "Bearish trigger is an active close below stored bearish rejection low.",
    "UT Bot and SMI are alternative confirmations; confirmation score must be >= 1.",
    "UT Bot uses sensitivity 1.0 and ATR length 10 with persistent UT stop state.",
    "SMI uses 7-2-2; bullish requires main > signal and main > main[1], bearish requires main < signal and main < main[1].",
    "A trade signal is created only on the false → true transition of longSignal or shortSignal.",
    "Entry is locked to the signal candle close.",
  ],
  optionalConfluence: ["Supply & Demand is optional confluence and cannot create an EMA20 trade."],
  invalidationRules: [
    "Long rejection: close < stored bullish rejection low.",
    "Short rejection: close > stored bearish rejection high.",
    "Long/short rejection expires when bar_index - rejectionBar > confirmationBars.",
    "A signal requires positive calculated risk.",
  ],
  executionRules: [
    "Long entry = signal candle close.",
    "Short entry = signal candle close.",
    "Long SL = entry − (ATR14 × 2.23).",
    "Short SL = entry + (ATR14 × 2.23).",
    "Long TP = entry + (entry − SL) × 1.81.",
    "Short TP = entry − (SL − entry) × 1.81.",
    "Do not shift historical entry, SL or TP after the signal candle.",
    "06:00 SAST bias is display-only and must never block a valid EMA20 trade.",
  ],
  riskRules: [
    "ATR stop-loss multiplier = 2.23.",
    "Risk must be positive.",
    "Risk/reward ratio = 1:1.81.",
    "The strategy does not define an account-risk percentage; account value/risk percentage belongs to position sizing, not signal qualification.",
  ],
  aiInstructions: [
    "The supplied Pine Script is authoritative.",
    "Do not call BUY/SELL from EMA position alone.",
    "Do not require both UT Bot and SMI; one confirmation is sufficient.",
    "Do not use EMA105 as an entry filter; it is context only.",
    "Do not replace the ATR-based SL with rejection-high/low stops.",
    "Do not replace 1:1.81 RR with a generic 1:2 rule.",
    "Explain the current lifecycle stage and the exact missing condition.",
  ],
};

export default ema20Rules;
