/** VaultTrades — Sweep & Engulfing. Exact source: library sweepEngulfing.txt, 2,468 lines. */
import type { StrategyRuleSet } from "./types";
export const SWEEP_ENGULFING_ID="sweepEngulfing" as const;
export const SWEEP_ENGULFING_NAME="Sweep and Engulfing" as const;
export type SweepCandle={open:number;high:number;low:number;close:number;volume?:number;time?:number|string};
export type StopLossMethod="ATR"|"Sweep";
export type PreviousCandleDirection="Same Direction"|"Opposite Direction"|"Any";
export interface SweepEngulfingSettings{enableEngine:boolean;accountRiskPercent:number;minimumRR:number;maxDrawdown:number;stopLossMethod:StopLossMethod;atrLength:number;atrMultiplier:number;tpMultiplier:number;externalSwingLength:number;internalSwingLength:number;bosLookback:number;trendEMA:number;requireLiquiditySweep:boolean;sweepConfirmationBody:boolean;sweepValidityBars:number;volumeLength:number;volumeSpikeMultiplier:number;zoneVolumeWeight:number;minimumVolumeScore:number;requireVolumeConfirmation:boolean;confirmationCandles:number;requireEngulfing:boolean;useEMAFilter:boolean;invertStrategy:boolean;previousCandleDirection:PreviousCandleDirection;engulfBodyMultiplier:number;engulfATRMultiplier:number;requireFullBodyEngulf:boolean;srLookback:number;srToleranceATR:number;srMinimumScore:number}
export const DEFAULT_SWEEP_ENGULFING_SETTINGS:SweepEngulfingSettings={enableEngine:true,accountRiskPercent:.5,minimumRR:1.63,maxDrawdown:5,stopLossMethod:"ATR",atrLength:14,atrMultiplier:1.8,tpMultiplier:2,externalSwingLength:10,internalSwingLength:3,bosLookback:50,trendEMA:200,requireLiquiditySweep:true,sweepConfirmationBody:true,sweepValidityBars:3,volumeLength:20,volumeSpikeMultiplier:1.5,zoneVolumeWeight:35,minimumVolumeScore:70,requireVolumeConfirmation:false,confirmationCandles:2,requireEngulfing:true,useEMAFilter:true,invertStrategy:false,previousCandleDirection:"Same Direction",engulfBodyMultiplier:1.2,engulfATRMultiplier:.5,requireFullBodyEngulf:true,srLookback:50,srToleranceATR:.25,srMinimumScore:40};
export interface SweepEngulfingInput{candles:SweepCandle[];settings?:Partial<SweepEngulfingSettings>}
export interface SweepEngulfingResult{strategyId:typeof SWEEP_ENGULFING_ID;strategyName:typeof SWEEP_ENGULFING_NAME;direction:"LONG"|"SHORT"|"NONE";signal:"BUY"|"SELL"|"WAIT";isNewSignal:boolean;entryPrice:number|null;stopLoss:number|null;target1:number|null;target2:number|null;target3:number|null;riskReward:number|null;confidence:null;structure:any;liquidity:any;engulfing:any;volume:any;opposingLiquidity:number|null;support:any;resistance:any;evidence:string[];invalidation:string[];message:string}
interface State{externalHigh:number|null;externalLow:number|null;previousExternalHigh:number|null;previousExternalLow:number|null;externalHighBar:number|null;externalLowBar:number|null;internalHigh:number|null;internalLow:number|null;trend:-1|0|1;bullSweepBar:number|null;bearSweepBar:number|null;bullSweepPrice:number|null;bearSweepPrice:number|null;prevLong:boolean;prevShort:boolean}
const initial=():State=>({externalHigh:null,externalLow:null,previousExternalHigh:null,previousExternalLow:null,externalHighBar:null,externalLowBar:null,internalHigh:null,internalLow:null,trend:0,bullSweepBar:null,bearSweepBar:null,bullSweepPrice:null,bearSweepPrice:null,prevLong:false,prevShort:false});
function ema(v:number[],n:number){const r=new Array<number>(v.length);if(!v.length)return r;const a=2/(n+1);r[0]=v[0];for(let i=1;i<v.length;i++)r[i]=a*v[i]+(1-a)*r[i-1];return r}
function sma(v:number[],n:number,i:number){if(i+1<n)return NaN;let x=0;for(let j=i-n+1;j<=i;j++)x+=v[j];return x/n}
function rma(v:number[],n:number){const r=new Array<number>(v.length).fill(NaN);let sum=0;for(let i=0;i<v.length;i++){if(i<n){sum+=v[i];if(i===n-1)r[i]=sum/n}else r[i]=(r[i-1]*(n-1)+v[i])/n}return r}
function atr(c:SweepCandle[],n:number){const tr=c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low);return rma(tr,n)}
function ph(c:SweepCandle[],i:number,n:number){if(i<n||i+n>=c.length)return false;for(let j=i-n;j<=i+n;j++)if(j!==i&&c[j].high>=c[i].high)return false;return true}
function pl(c:SweepCandle[],i:number,n:number){if(i<n||i+n>=c.length)return false;for(let j=i-n;j<=i+n;j++)if(j!==i&&c[j].low<=c[i].low)return false;return true}
function nearestHigh(e:number,a:number|null,b:number|null){const q=[a,b].filter((x):x is number=>x!==null&&x>e);return q.length?Math.min(...q):null}
function nearestLow(e:number,a:number|null,b:number|null){const q=[a,b].filter((x):x is number=>x!==null&&x<e);return q.length?Math.max(...q):null}
function sr(c:SweepCandle[],level:number|null,a:number,s:number,t:number,support:boolean){if(level===null)return{score:0,touch:false,reaction:false};const tol=a*t,start=Math.max(0,c.length-s),vol=c.map(x=>x.volume??0),av=vol.length?vol.reduce((x,y)=>x+y,0)/vol.length:0;let tc=0,rc=0,vc=0,lt=false,lr=false;for(let i=start;i<c.length;i++){const x=c[i],touch=support?x.low<=level+tol&&x.high>=level-tol:x.high>=level-tol&&x.low<=level+tol,reaction=support?touch&&x.close>level:touch&&x.close<level;if(touch)tc++;if(reaction)rc++;if(reaction&&av>0&&(x.volume??0)/av>=1)vc++;if(i===c.length-1){lt=touch;lr=reaction}}return{score:Math.min(100,Math.min(tc*10,40)+Math.min(rc*10,35)+Math.min(vc*5,25)),touch:lt,reaction:lr}}
function status(n:number){return n>=80?"VERY STRONG":n>=65?"STRONG":n>=50?"MODERATE":"WEAK"}
function empty():SweepEngulfingResult{return{strategyId:SWEEP_ENGULFING_ID,strategyName:SWEEP_ENGULFING_NAME,direction:"NONE",signal:"WAIT",isNewSignal:false,entryPrice:null,stopLoss:null,target1:null,target2:null,target3:null,riskReward:null,confidence:null,structure:{},liquidity:{},engulfing:{},volume:{},opposingLiquidity:null,support:{},resistance:{},evidence:[],invalidation:[],message:"WAIT"}}
export function analyzeSweepEngulfing(input:SweepEngulfingInput):SweepEngulfingResult{const s={...DEFAULT_SWEEP_ENGULFING_SETTINGS,...(input.settings??{})},c=input.candles;if(!c.length)return empty();const st=initial();let out=empty();for(let i=0;i<c.length;i++)out=bar(c,i,s,st);return out}
function bar(c:SweepCandle[],i:number,s:SweepEngulfingSettings,st:State):SweepEngulfingResult{
 const x=c[i],p=i?c[i-1]:null,a=atr(c.slice(0,i+1),s.atrLength)[i],av=sma(c.slice(0,i+1).map(q=>q.volume??0),s.volumeLength,i),rv=Number.isFinite(av)&&av>0?(x.volume??0)/av:0,vs=Math.min(100,rv/s.volumeSpikeMultiplier*100),inst=rv>=s.volumeSpikeMultiplier,volumeOK=!s.requireVolumeConfirmation||vs>=s.minimumVolumeScore,trend=ema(c.slice(0,i+1).map(q=>q.close),s.trendEMA)[i];
 const oldH=st.externalHigh,oldL=st.externalLow,oldHB=st.externalHighBar,oldLB=st.externalLowBar,oldTrend=st.trend,ep=i-s.externalSwingLength,ip=i-s.internalSwingLength;let HH=false,LH=false,HL=false,LL=false;
 if(ep>=0&&ph(c,ep,s.externalSwingLength)){st.previousExternalHigh=st.externalHigh;st.externalHigh=c[ep].high;st.externalHighBar=ep}if(ep>=0&&pl(c,ep,s.externalSwingLength)){st.previousExternalLow=st.externalLow;st.externalLow=c[ep].low;st.externalLowBar=ep}if(ip>=0&&ph(c,ip,s.internalSwingLength))st.internalHigh=c[ip].high;if(ip>=0&&pl(c,ip,s.internalSwingLength))st.internalLow=c[ip].low;
 if(st.previousExternalHigh!==null&&st.externalHigh!==null){HH=st.externalHigh>st.previousExternalHigh;LH=st.externalHigh<st.previousExternalHigh}if(st.previousExternalLow!==null&&st.externalLow!==null){HL=st.externalLow>st.previousExternalLow;LL=st.externalLow<st.previousExternalLow}if(HH&&HL)st.trend=1;if(LH&&LL)st.trend=-1;
 const bullBreak=oldH!==null&&p!==null&&x.close>oldH&&p.close<=oldH,bearBreak=oldL!==null&&p!==null&&x.close<oldL&&p.close>=oldL;let bullBOS=false,bearBOS=false,bullCHOCH=false,bearCHOCH=false,bullMSS=false,bearMSS=false;if(bullBreak){if(oldTrend===-1){bullCHOCH=true;bullMSS=true}else bullBOS=true;st.trend=1}if(bearBreak){if(oldTrend===1){bearCHOCH=true;bearMSS=true}else bearBOS=true;st.trend=-1}
 const sweepL=oldL,sweepH=oldH,bullSweep=sweepL!==null&&x.low<sweepL&&x.close>sweepL,bearSweep=sweepH!==null&&x.high>sweepH&&x.close<sweepH,bullConfirmed=bullSweep&&(!s.sweepConfirmationBody||x.close>x.open),bearConfirmed=bearSweep&&(!s.sweepConfirmationBody||x.close<x.open);if(bullConfirmed){st.bullSweepBar=i;st.bullSweepPrice=x.low}if(bearConfirmed){st.bearSweepBar=i;st.bearSweepPrice=x.high}const bullActive=st.bullSweepBar!==null&&i-st.bullSweepBar<=s.sweepValidityBars,bearActive=st.bearSweepBar!==null&&i-st.bearSweepBar<=s.sweepValidityBars;
 const body=Math.abs(x.close-x.open),prevBody=p?Math.abs(p.close-p.open):0,currentBull=x.close>x.open,currentBear=x.close<x.open,bullBodyStrong=currentBull&&body>=a*s.engulfATRMultiplier,bearBodyStrong=currentBear&&body>=a*s.engulfATRMultiplier,bullExpand=currentBull&&(prevBody<=0||body>=prevBody*s.engulfBodyMultiplier),bearExpand=currentBear&&(prevBody<=0||body>=prevBody*s.engulfBodyMultiplier),bullPrevOK=s.previousCandleDirection==="Any"||(s.previousCandleDirection==="Opposite Direction"?(p?.close??0)<(p?.open??0):(p?.close??0)>(p?.open??0)),bearPrevOK=s.previousCandleDirection==="Any"||(s.previousCandleDirection==="Opposite Direction"?(p?.close??0)>(p?.open??0):(p?.close??0)<(p?.open??0));const strongBull=currentBull&&bullBodyStrong&&bullExpand&&volumeOK&&bullPrevOK,strongBear=currentBear&&bearBodyStrong&&bearExpand&&volumeOK&&bearPrevOK;
 const longEMA=!s.useEMAFilter||x.close>trend,shortEMA=!s.useEMAFilter||x.close<trend,entry=x.close,longTarget=nearestHigh(entry,st.externalHigh,st.previousExternalHigh),shortTarget=nearestLow(entry,st.externalLow,st.previousExternalLow),longStop=s.stopLossMethod==="ATR"?entry-a*s.atrMultiplier:(st.bullSweepPrice!==null?st.bullSweepPrice-a*.10:entry-a*s.atrMultiplier),shortStop=s.stopLossMethod==="ATR"?entry+a*s.atrMultiplier:(st.bearSweepPrice!==null?st.bearSweepPrice+a*.10:entry+a*s.atrMultiplier),longRisk=entry-longStop,shortRisk=shortStop-entry,longRR=longTarget!==null&&longRisk>Number.EPSILON?(longTarget-entry)/longRisk:NaN,shortRR=shortTarget!==null&&shortRisk>Number.EPSILON?(entry-shortTarget)/shortRisk:NaN;
 const longSE=bullActive&&strongBull,shortSE=bearActive&&strongBear,longBase=s.enableEngine&&longSE&&longEMA&&volumeOK&&longTarget!==null&&longTarget>entry&&longRR>=s.minimumRR,shortBase=s.enableEngine&&shortSE&&shortEMA&&volumeOK&&shortTarget!==null&&shortTarget<entry&&shortRR>=s.minimumRR,rawLong=s.requireLiquiditySweep?longBase:strongBull&&longEMA&&volumeOK,rawShort=s.requireLiquiditySweep?shortBase:strongBear&&shortEMA&&volumeOK,finalLong=s.invertStrategy?rawShort:rawLong,finalShort=s.invertStrategy?rawLong:rawShort,longSignal=finalLong&&!st.prevLong,shortSignal=finalShort&&!st.prevShort;st.prevLong=finalLong;st.prevShort=finalShort;
 const signal=longSignal?"BUY":shortSignal?"SELL":"WAIT",direction=finalLong||longSignal?"LONG":finalShort||shortSignal?"SHORT":"NONE",target=longSignal?longTarget:shortSignal?shortTarget:null,stop=longSignal?longStop:shortSignal?shortStop:null,rr=longSignal?longRR:shortSignal?shortRR:null,sup=sr(c,st.externalLow,a,s.srLookback,s.srToleranceATR,true),res=sr(c,st.externalHigh,a,s.srLookback,s.srToleranceATR,false),bias=st.trend===1?"Bullish":st.trend===-1?"Bearish":"Neutral";
 const evidence:string[]=[],missing:string[]=[];if(bullConfirmed)evidence.push("Sell-side liquidity swept and bullish sweep candle confirmed.");if(bearConfirmed)evidence.push("Buy-side liquidity swept and bearish sweep candle confirmed.");if(strongBull)evidence.push("Bullish displacement/engulfing confirmation satisfied.");if(strongBear)evidence.push("Bearish displacement/engulfing confirmation satisfied.");if(bullBOS||bullCHOCH)evidence.push("Bullish BOS/CHOCH event confirmed.");if(bearBOS||bearCHOCH)evidence.push("Bearish BOS/CHOCH event confirmed.");if(longTarget!==null)evidence.push(`Nearest opposing buy-side liquidity: ${longTarget}.`);if(shortTarget!==null)evidence.push(`Nearest opposing sell-side liquidity: ${shortTarget}.`);if(longSignal)evidence.push("NEW BUY event.");if(shortSignal)evidence.push("NEW SELL event.");if(s.requireLiquiditySweep&&!bullActive&&!bearActive)missing.push("Valid liquidity sweep.");if(!strongBull&&!strongBear)missing.push("Strong displacement/engulfing confirmation.");if(s.useEMAFilter&&!longEMA&&!shortEMA)missing.push("EMA 200 filter.");if(s.requireVolumeConfirmation&&!volumeOK)missing.push("Volume confirmation.");
 const event=bullCHOCH?"BULL CHOCH":bearCHOCH?"BEAR CHOCH":bullBOS?"BULL BOS":bearBOS?"BEAR BOS":"NONE";
 return{strategyId:SWEEP_ENGULFING_ID,strategyName:SWEEP_ENGULFING_NAME,direction,signal,isNewSignal:longSignal||shortSignal,entryPrice:longSignal||shortSignal?entry:null,stopLoss:longSignal||shortSignal?stop:null,target1:longSignal||shortSignal?target:null,target2:longSignal?entry+longRisk*Math.max(s.minimumRR+.5,s.tpMultiplier+.5):shortSignal?entry-shortRisk*Math.max(s.minimumRR+.5,s.tpMultiplier+.5):null,target3:longSignal?entry+longRisk*Math.max(s.minimumRR+1,s.tpMultiplier+1):shortSignal?entry-shortRisk*Math.max(s.minimumRR+1,s.tpMultiplier+1):null,riskReward:longSignal||shortSignal?rr:null,confidence:null,structure:{bias,trend:st.trend,event,bullishBOS:bullBOS,bearishBOS:bearBOS,bullishCHOCH:bullCHOCH,bearishCHOCH:bearCHOCH,bullishMSS:bullMSS,bearishMSS:bearMSS,externalHigh:st.externalHigh,externalLow:st.externalLow,previousExternalHigh:st.previousExternalHigh,previousExternalLow:st.previousExternalLow,higherHigh:HH,lowerHigh:LH,higherLow:HL,lowerLow:LL,strongHigh:st.trend===-1&&st.externalHigh!==null,weakHigh:st.trend===1&&st.externalHigh!==null,strongLow:st.trend===1&&st.externalLow!==null,weakLow:st.trend===-1&&st.externalLow!==null},liquidity:{bullishSweepConfirmed:bullConfirmed,bearishSweepConfirmed:bearConfirmed,bullishSweepActive:bullActive,bearishSweepActive:bearActive,bullishSweepPrice:st.bullSweepPrice,bearishSweepPrice:st.bearSweepPrice},engulfing:{bullish:strongBull,bearish:strongBear,body,previousBody:prevBody,bodyVsATR:a>0?body/a:0,bodyExpansion:bullExpand||bearExpand},volume:{averageVolume:Number.isFinite(av)?av:0,relativeVolume:rv,institutionalVolume:inst,volumeScore:vs,volumeConfirmed:volumeOK},opposingLiquidity:target,support:{level:st.externalLow,strength:sup.score,status:status(sup.score),touch:sup.touch,reaction:sup.reaction},resistance:{level:st.externalHigh,strength:res.score,status:status(res.score),touch:res.touch,reaction:res.reaction},evidence,invalidation:missing,message:longSignal?"BUY — sweep + strong displacement/engulfing + opposing liquidity + minimum RR.":shortSignal?"SELL — sweep + strong displacement/engulfing + opposing liquidity + minimum RR.":finalLong?"LONG QUALIFIED — waiting for the one-shot BUY event.":finalShort?"SHORT QUALIFIED — waiting for the one-shot SELL event.":bullActive?"BULLISH SWEEP ACTIVE — waiting for strong displacement/engulfing.":bearActive?"BEARISH SWEEP ACTIVE — waiting for strong displacement/engulfing.":"WAIT — no qualified Sweep & Engulfing entry."};
}
export const sweepEngulfingRules:StrategyRuleSet={id:SWEEP_ENGULFING_ID,name:SWEEP_ENGULFING_NAME,description:"Institutional Liquidity Sweep + Strong Engulfing/Displacement + Opposing Liquidity",source:"PINE_SCRIPT",timeframes:["chart"],sequence:["Confirmed external structure","Liquidity sweep","Sweep confirmation","Strong displacement/engulfing","EMA/volume filters","Opposing liquidity","Minimum RR","One-shot BUY/SELL"],mandatoryRules:["Bullish sweep: current low below previous-bar confirmed external low and close back above it.","Bearish sweep: current high above previous-bar confirmed external high and close back below it.","Strong confirmation uses candle body vs ATR, body expansion and directional confirmation; it is not a textbook full-body engulf requirement.","When sweep is required, opposing liquidity and minimum RR 1.63 must qualify.","BUY/SELL are events, not persistent states."],optionalConfluence:["EMA 200 filter","Institutional volume confirmation","Support/resistance strength display"],invalidationRules:["No valid sweep when required","No strong displacement confirmation","EMA filter failure","Volume failure when enabled","No opposing liquidity or insufficient RR"],executionRules:["Normal mode maps bullish qualified setup to LONG and bearish to SHORT.","Invert Strategy swaps final directions after qualification.","One-shot signal is final condition true while previous final condition was false."],riskRules:["Default risk per trade is 0.50%.","Default stop method is ATR with 1.8 ATR multiplier.","Sweep stop uses sweep price +/- 0.10 ATR.","Minimum RR is 1.63.","TP1 is opposing liquidity; TP2/TP3 use the Pine formulas."],aiInstructions:["The selected strategy is the source of truth.","Do not turn BOS/CHOCH or S/R strength into entries by themselves.","Support/resistance strength is display-only and does not modify entry, risk or targets."]};
export const sweepEngulfingStrategy={id:SWEEP_ENGULFING_ID,name:SWEEP_ENGULFING_NAME,description:sweepEngulfingRules.description,timeframes:["chart"] as const,analyze:analyzeSweepEngulfing,rules:sweepEngulfingRules};
export default sweepEngulfingStrategy;
