/**
 * VaultTrades — Swing Developing Strategy
 * Source of truth: supplied Pine Script v6 "Swing Developing Strategy" (1,106 lines).
 * H1 direction -> M15 alignment -> EMA 9/15 pullback -> recovery -> M15 SMI -> entry event.
 * Source Pine defines no SL/TP/RR.
 */
import type { StrategyRuleSet } from "./types";
export const SWING_DEVELOPING_ID="swingDeveloping" as const;
export const SWING_DEVELOPING_NAME="Swing Developing Strategy" as const;
export type SwingCandle={time?:number|string;open:number;high:number;low:number;close:number;volume?:number};
export type SwingStage="WAIT"|"DIRECTION"|"PULLBACK"|"ENTRY_READY"|"ENTER_LONG"|"ENTER_SHORT";
export interface SwingDevelopingSettings{emaFastLen:number;emaSlowLen:number;emaTrendLen:number;smiLength:number;smiSmooth1:number;smiSmooth2:number;smiOB:number;smiOS:number;requireEMA100:boolean;requirePullback:boolean}
export interface SwingDevelopingInput{h1:SwingCandle[];m15:SwingCandle[];current?:SwingCandle;settings?:Partial<SwingDevelopingSettings>}
export interface SwingState{close:number;ema9:number;ema15:number;ema100:number;smi:number;bullish:boolean;bearish:boolean;above100:boolean;below100:boolean;longDirection:boolean;shortDirection:boolean}
export interface SwingDevelopingResult{strategyId:typeof SWING_DEVELOPING_ID;strategyName:typeof SWING_DEVELOPING_NAME;direction:"LONG"|"SHORT"|"NEUTRAL";stage:SwingStage;signal:"BUY"|"SELL"|"NONE";isNewSignal:boolean;entryPrice:number|null;stopLoss:null;takeProfit:null;riskReward:null;confidence:null;h1:SwingState;m15:SwingState;pullback:{long:boolean;short:boolean;active:boolean};recovery:{long:boolean;short:boolean;longTrigger:boolean;shortTrigger:boolean};momentum:{long:boolean;short:boolean;h1SMI:number;m15SMI:number};states:{longSetupDeveloping:boolean;shortSetupDeveloping:boolean;longWatch:boolean;shortWatch:boolean;longEntryReady:boolean;shortEntryReady:boolean;longEntry:boolean;shortEntry:boolean;longSignal:boolean;shortSignal:boolean};evidence:string[];invalidation:string[];message:string}
const D:SwingDevelopingSettings={emaFastLen:9,emaSlowLen:15,emaTrendLen:100,smiLength:7,smiSmooth1:2,smiSmooth2:2,smiOB:40,smiOS:-40,requireEMA100:true,requirePullback:true};
function ema(v:number[],n:number){const r=new Array<number>(v.length);if(!v.length)return r;const a=2/(n+1);r[0]=v[0];for(let i=1;i<v.length;i++)r[i]=a*v[i]+(1-a)*r[i-1];return r}
function hi(v:number[],n:number){return v.map((_,i)=>{let x=-Infinity;for(let j=Math.max(0,i-n+1);j<=i;j++)x=Math.max(x,v[j]);return x})}
function lo(v:number[],n:number){return v.map((_,i)=>{let x=Infinity;for(let j=Math.max(0,i-n+1);j<=i;j++)x=Math.min(x,v[j]);return x})}
function smi(c:SwingCandle[],n:number,s1:number,s2:number){const h=hi(c.map(x=>x.high),n),l=lo(c.map(x=>x.low),n),rel=c.map((x,i)=>x.close-(h[i]+l[i])/2),dist=c.map((_,i)=>(h[i]-l[i])/2),rs=ema(ema(rel,s1),s2),ds=ema(ema(dist,s1),s2);return rs.map((x,i)=>ds[i]===0?0:100*x/ds[i])}
function build(c:SwingCandle[],s:SwingDevelopingSettings){const cl=c.map(x=>x.close),e9=ema(cl,s.emaFastLen),e15=ema(cl,s.emaSlowLen),e100=ema(cl,s.emaTrendLen),m=smi(c,s.smiLength,s.smiSmooth1,s.smiSmooth2);return c.map((x,i):SwingState=>{const bull=e9[i]>e15[i],bear=e9[i]<e15[i],above=x.close>e100[i],below=x.close<e100[i];return{close:x.close,ema9:e9[i],ema15:e15[i],ema100:e100[i],smi:m[i],bullish:bull,bearish:bear,above100:above,below100:below,longDirection:bull&&(!s.requireEMA100||above),shortDirection:bear&&(!s.requireEMA100||below)}})}
const E=():SwingState=>({close:0,ema9:0,ema15:0,ema100:0,smi:0,bullish:false,bearish:false,above100:false,below100:false,longDirection:false,shortDirection:false});
export function analyzeSwingDeveloping(input:SwingDevelopingInput):SwingDevelopingResult{
 const s={...D,...(input.settings??{})},hs=build(input.h1,s),ms=build(input.m15,s),h=hs[hs.length-1],m=ms[ms.length-1];
 if(!h||!m)return{strategyId:SWING_DEVELOPING_ID,strategyName:SWING_DEVELOPING_NAME,direction:"NEUTRAL",stage:"WAIT",signal:"NONE",isNewSignal:false,entryPrice:null,stopLoss:null,takeProfit:null,riskReward:null,confidence:null,h1:h??E(),m15:m??E(),pullback:{long:false,short:false,active:false},recovery:{long:false,short:false,longTrigger:false,shortTrigger:false},momentum:{long:false,short:false,h1SMI:h?.smi??0,m15SMI:m?.smi??0},states:{longSetupDeveloping:false,shortSetupDeveloping:false,longWatch:false,shortWatch:false,longEntryReady:false,shortEntryReady:false,longEntry:false,shortEntry:false,longSignal:false,shortSignal:false},evidence:["Insufficient H1/M15 data."],invalidation:["Provide sufficient H1 and M15 candles."],message:"WAIT — insufficient H1/M15 data."};
 const n=ms.length,ld=Array(n).fill(false),sd=Array(n).fill(false),lw=Array(n).fill(false),sw=Array(n).fill(false),lr=Array(n).fill(false),sr=Array(n).fill(false),lm=Array(n).fill(false),sm=Array(n).fill(false),le=Array(n).fill(false),se=Array(n).fill(false);
 for(let i=0;i<n;i++){const x=ms[i];ld[i]=h.longDirection&&x.longDirection;sd[i]=h.shortDirection&&x.shortDirection;const pL=x.close<=x.ema9||x.close<=x.ema15,pS=x.close>=x.ema9||x.close>=x.ema15;lw[i]=ld[i]&&pL;sw[i]=sd[i]&&pS;lr[i]=x.close>x.ema9;sr[i]=x.close<x.ema9;lm[i]=x.smi>=s.smiOB;sm[i]=x.smi<=s.smiOS;le[i]=ld[i]&&(i>0?lw[i-1]:false)&&lr[i]&&lm[i];se[i]=sd[i]&&(i>0?sw[i-1]:false)&&sr[i]&&sm[i]}
 const i=n-1,longDirection=ld[i],shortDirection=sd[i],longWatch=lw[i],shortWatch=sw[i],longRecovery=lr[i],shortRecovery=sr[i],longTrigger=i>0&&lw[i-1]&&lr[i],shortTrigger=i>0&&sw[i-1]&&sr[i],longEntry=le[i],shortEntry=se[i],longSignal=longEntry&&!((i>0&&le[i-1])||false),shortSignal=shortEntry&&!((i>0&&se[i-1])||false),longReady=longWatch&&!longRecovery,shortReady=shortWatch&&!shortRecovery,longDev=longDirection&&!longWatch,shortDev=shortDirection&&!shortWatch;
 let direction:"LONG"|"SHORT"|"NEUTRAL"="NEUTRAL",stage:SwingStage="WAIT",signal:"BUY"|"SELL"|"NONE"="NONE";
 if(longSignal){direction="LONG";stage="ENTER_LONG";signal="BUY"}else if(shortSignal){direction="SHORT";stage="ENTER_SHORT";signal="SELL"}else if(longReady){direction="LONG";stage="ENTRY_READY"}else if(shortReady){direction="SHORT";stage="ENTRY_READY"}else if(longWatch){direction="LONG";stage="PULLBACK"}else if(shortWatch){direction="SHORT";stage="PULLBACK"}else if(longDev){direction="LONG";stage="DIRECTION"}else if(shortDev){direction="SHORT";stage="DIRECTION"}
 const evidence:string[]=[],missing:string[]=[];if(h.longDirection)evidence.push("H1 bullish direction confirmed.");if(h.shortDirection)evidence.push("H1 bearish direction confirmed.");if(m.longDirection)evidence.push("M15 bullish direction aligned with H1.");if(m.shortDirection)evidence.push("M15 bearish direction aligned with H1.");if(longWatch)evidence.push("M15 bullish EMA 9/15 pullback active.");if(shortWatch)evidence.push("M15 bearish EMA 9/15 pullback active.");if(longTrigger)evidence.push("M15 recovered above EMA 9 after the prior bullish pullback.");if(shortTrigger)evidence.push("M15 recovered below EMA 9 after the prior bearish pullback.");if(lm[i])evidence.push(`M15 SMI ${m.smi.toFixed(1)} >= ${s.smiOB}.`);if(sm[i])evidence.push(`M15 SMI ${m.smi.toFixed(1)} <= ${s.smiOS}.`);if(longSignal)evidence.push("NEW BUY transition confirmed.");if(shortSignal)evidence.push("NEW SELL transition confirmed.");
 if(!longDirection&&!shortDirection)missing.push("H1 + M15 alignment.");if(longDirection&&!longWatch)missing.push("M15 bullish EMA 9/15 pullback.");if(shortDirection&&!shortWatch)missing.push("M15 bearish EMA 9/15 pullback.");if(longReady)missing.push(`Recovery above EMA 9 with SMI >= ${s.smiOB}.`);if(shortReady)missing.push(`Recovery below EMA 9 with SMI <= ${s.smiOS}.`);
 let message="WAIT";if(longSignal)message="ENTER LONG — H1 bullish + M15 bullish + prior pullback + recovery above EMA 9 + bullish SMI.";else if(shortSignal)message="ENTER SHORT — H1 bearish + M15 bearish + prior pullback + recovery below EMA 9 + bearish SMI.";else if(longReady)message="LONG ENTRY READY — wait for recovery above EMA 9 with SMI confirmation.";else if(shortReady)message="SHORT ENTRY READY — wait for recovery below EMA 9 with SMI confirmation.";else if(longWatch)message="LONG PULLBACK — bullish swing direction confirmed.";else if(shortWatch)message="SHORT PULLBACK — bearish swing direction confirmed.";else if(longDev)message="LONG DIRECTION — H1 + M15 aligned; wait for EMA 9/15 pullback.";else if(shortDev)message="SHORT DIRECTION — H1 + M15 aligned; wait for EMA 9/15 pullback.";
 return{strategyId:SWING_DEVELOPING_ID,strategyName:SWING_DEVELOPING_NAME,direction,stage,signal,isNewSignal:longSignal||shortSignal,entryPrice:longSignal||shortSignal?(input.current?.close??m.close):null,stopLoss:null,takeProfit:null,riskReward:null,confidence:null,h1:h,m15:m,pullback:{long:m.close<=m.ema9||m.close<=m.ema15,short:m.close>=m.ema9||m.close>=m.ema15,active:longWatch||shortWatch},recovery:{long:longRecovery,short:shortRecovery,longTrigger:longTrigger,shortTrigger:shortTrigger},momentum:{long:lm[i],short:sm[i],h1SMI:h.smi,m15SMI:m.smi},states:{longSetupDeveloping:longDev,shortSetupDeveloping:shortDev,longWatch,shortWatch,longEntryReady:longReady,shortEntryReady:shortReady,longEntry,shortEntry,longSignal,shortSignal},evidence,invalidation:missing,message};
}
export const swingDevelopingRules:StrategyRuleSet={id:SWING_DEVELOPING_ID,name:SWING_DEVELOPING_NAME,description:"H1 + M15 swing direction with EMA 9/15 pullback, recovery and M15 SMI 7-2-2 confirmation.",source:"PINE_SCRIPT",timeframes:["H1","M15"],sequence:["H1 direction","M15 alignment","EMA 9/15 pullback","Recovery through EMA 9","M15 SMI confirmation","NEW BUY/SELL"],mandatoryRules:["H1 EMA 9/15 direction with optional EMA 100 filter.","M15 must agree with H1.","A prior M15 pullback is required by the Pine entry transition.","Current M15 candle must recover through EMA 9.","M15 SMI >= +40 for long or <= -40 for short.","Signal is longEntry and not longEntry[1], or shortEntry and not shortEntry[1]."],optionalConfluence:["EMA 100 filter can be disabled by the Pine input."],invalidationRules:["No H1/M15 alignment","No prior pullback","No recovery","No SMI confirmation"],executionRules:["Only final BUY/SELL signal is an entry event."],riskRules:["No SL/TP/RR exists in the source Pine strategy."],aiInstructions:["Treat DIRECTION, PULLBACK and ENTRY READY as non-entry states.","Do not invent risk management or confidence." ]};
export const swingDevelopingStrategy={id:SWING_DEVELOPING_ID,name:SWING_DEVELOPING_NAME,description:swingDevelopingRules.description,timeframes:["H1","M15"] as const,analyze:analyzeSwingDeveloping,rules:swingDevelopingRules};
export default swingDevelopingStrategy;
