"use client";

import { useMemo, useState } from "react";

type Props = { initialEntry?: number | null; initialStop?: number | null; initialTp1?: number | null; initialTp2?: number | null; symbol?: string };
const num=(v:string)=>{const n=Number(v);return Number.isFinite(n)?n:0};
const money=(v:number)=>v.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2});
const fmt=(v:number,d=2)=>v.toLocaleString(undefined,{maximumFractionDigits:d});

export default function RiskManager({initialEntry=null,initialStop=null,initialTp1=null,initialTp2=null,symbol="XAU/USD"}:Props){
 const [type,setType]=useState<"PERSONAL"|"PROP">("PERSONAL");
 const [account,setAccount]=useState(10000),[margin,setMargin]=useState(10000),[dailyUsed,setDailyUsed]=useState(0),[dailyLimit,setDailyLimit]=useState(1),[riskPct,setRiskPct]=useState(.5),[maxCapital,setMaxCapital]=useState(10);
 const [entry,setEntry]=useState(initialEntry??0),[sl,setSl]=useState(initialStop??0),[tp1,setTp1]=useState(initialTp1??0),[tp2,setTp2]=useState(initialTp2??0);
 const [valuePerMove,setValuePerMove]=useState(100),[marginPerLot,setMarginPerLot]=useState(1000),[lotStep,setLotStep]=useState(.01);
 const calc=useMemo(()=>{const dailyAllowance=account*Math.max(0,dailyLimit)/100,dailyRemaining=Math.max(0,dailyAllowance-Math.max(0,dailyUsed)),tradeCap=account*Math.min(Math.max(0,riskPct),Math.max(0,maxCapital))/100,budget=Math.min(tradeCap,dailyRemaining),distance=Math.abs(entry-sl),riskLot=distance*Math.max(0,valuePerMove),riskLots=riskLot>0?budget/riskLot:0,marginLots=marginPerLot>0?Math.max(0,margin)/marginPerLot:0,raw=Math.min(riskLots,marginLots),lots=lotStep>0?Math.max(0,Math.floor(raw/lotStep+1e-9)*lotStep):raw,loss=lots*riskLot,used=lots*marginPerLot,r1=distance>0?Math.abs(tp1-entry)/distance:0,r2=distance>0?Math.abs(tp2-entry)/distance:0;return{dailyAllowance,dailyRemaining,budget,distance,riskLot,riskLots,marginLots,lots,loss,used,marginAfter:Math.max(0,margin-used),riskAccount:account?loss/account*100:0,r1,r2,limited:riskLots<=marginLots?"risk budget":"margin available",valid:account>0&&margin>=0&&entry>0&&distance>0&&budget>0&&lots>0}},[account,margin,dailyUsed,dailyLimit,riskPct,maxCapital,entry,sl,tp1,tp2,valuePerMove,marginPerLot,lotStep]);
 const setTypeAndDefaults=(t:"PERSONAL"|"PROP")=>{setType(t);setDailyLimit(t==="PROP"?5:1);setRiskPct(.5)};
 const Field=({label,value,set,step="any"}:{label:string;value:number;set:(v:number)=>void;step?:string})=><label style={{display:"block"}}><span style={{color:"#aeb5c6",fontSize:10,fontWeight:800,letterSpacing:".08em"}}>{label}</span><input type="number" step={step} value={value} onChange={e=>set(num(e.target.value))} style={{width:"100%",marginTop:6,padding:"10px 11px",borderRadius:8,border:"1px solid rgba(212,166,55,.28)",background:"#050812",color:"#f4f6fb"}}/></label>;
 return <section className="card" style={{border:"1px solid rgba(212,166,55,.32)",background:"linear-gradient(145deg,rgba(10,16,30,.98),rgba(5,8,18,.98))"}}>
  <div className="section-label">VAULTTRADES RISK MANAGER</div>
  <div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap",alignItems:"center"}}><div><h2 className="title" style={{marginBottom:4}}>Position Size + Margin Risk Calculator</h2><p className="muted" style={{margin:0}}>Calculate lot size from account risk, stop distance and available margin before placing a trade.</p></div><div style={{display:"flex",gap:5}}>{(["PERSONAL","PROP"] as const).map(t=><button key={t} onClick={()=>setTypeAndDefaults(t)} style={{padding:"9px 13px",border:0,borderRadius:8,background:type===t?"#2d7dff":"#111827",color:"#fff",fontWeight:900}}>{t}</button>)}</div></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:11,marginTop:17}}><Field label="ACCOUNT SIZE ($)" value={account} set={setAccount}/><Field label="MARGIN AVAILABLE ($)" value={margin} set={setMargin}/><Field label="DAILY LOSS USED ($)" value={dailyUsed} set={setDailyUsed}/><Field label="DAILY LOSS LIMIT (%)" value={dailyLimit} set={setDailyLimit} step=".01"/><Field label="RISK PER TRADE (%)" value={riskPct} set={setRiskPct} step=".01"/><Field label="MAX CAPITAL RISK CEILING (%)" value={maxCapital} set={setMaxCapital} step=".01"/></div>
  <div style={{marginTop:16,padding:13,borderRadius:10,background:"rgba(45,125,255,.06)",border:"1px solid rgba(45,125,255,.22)"}}><div style={{color:"#d4a637",fontSize:10,fontWeight:900,letterSpacing:".12em",marginBottom:10}}>TRADE INPUT · {symbol}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(155px,1fr))",gap:11}}><Field label="ENTRY" value={entry} set={setEntry}/><Field label="STOP LOSS" value={sl} set={setSl}/><Field label="TP1" value={tp1} set={setTp1}/><Field label="TP2" value={tp2} set={setTp2}/><Field label="$ / PRICE UNIT / 1 LOT" value={valuePerMove} set={setValuePerMove}/><Field label="MARGIN / 1 LOT ($)" value={marginPerLot} set={setMarginPerLot}/><Field label="LOT STEP" value={lotStep} set={setLotStep} step=".01"/></div></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:9,marginTop:16}}>{[["RISK BUDGET",money(calc.budget)],["RECOMMENDED LOT SIZE",fmt(calc.lots,2)],["PROJECTED LOSS AT SL",money(calc.loss)],["MARGIN REQUIRED",money(calc.used)],["MARGIN AFTER ENTRY",money(calc.marginAfter)],["RISK / ACCOUNT",fmt(calc.riskAccount,2)+"%"]].map(([label,value])=><div key={label} style={{padding:12,borderRadius:9,border:"1px solid rgba(212,166,55,.28)",background:"rgba(255,255,255,.02)"}}><div style={{color:"#aeb5c6",fontSize:9,fontWeight:900,letterSpacing:".08em"}}>{label}</div><div style={{fontSize:21,fontWeight:950,marginTop:5}}>{value}</div></div>)}</div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:9,marginTop:12}}><div className="condition-box"><strong>Daily room</strong><p className="muted" style={{marginBottom:0}}>{money(calc.dailyRemaining)} remaining of {money(calc.dailyAllowance)}.</p></div><div className="condition-box"><strong>Position cap</strong><p className="muted" style={{marginBottom:0}}>Limited by {calc.limited}.</p></div><div className="condition-box"><strong>Stop distance</strong><p className="muted" style={{marginBottom:0}}>{fmt(calc.distance,5)} · {money(calc.riskLot)} risk per 1 lot.</p></div><div className="condition-box"><strong>Projected R:R</strong><p className="muted" style={{marginBottom:0}}>TP1 {fmt(calc.r1)}R · TP2 {fmt(calc.r2)}R.</p></div></div>
  <div style={{marginTop:14,padding:13,borderRadius:9,border:calc.valid?"1px solid rgba(40,200,110,.45)":"1px solid rgba(255,165,45,.45)",background:calc.valid?"rgba(40,200,110,.07)":"rgba(255,165,45,.07)"}}><strong>{calc.valid?("SIZE AVAILABLE: "+fmt(calc.lots,2)+" LOTS"):"ENTER VALID ACCOUNT, MARGIN, ENTRY AND STOP VALUES"}</strong><p className="muted" style={{margin:"6px 0 0"}}>{calc.valid?("A stop hit is approximately "+money(calc.loss)+" and uses "+money(calc.used)+" of available margin. Sizing is capped by the selected risk budget and available margin."):"This tool calculates position size only; it does not place trades."}</p></div>
  <p className="muted" style={{marginTop:13,fontSize:11,lineHeight:1.6}}>Broker and prop-firm margin rules, contract sizes, tick values and daily-loss definitions vary. Enter the live values supplied by the trading account. The calculator should not be treated as a guarantee of execution or as a substitute for the account's official rules.</p>
 </section>;
}
