"use client";

import { ChangeEvent, useState } from "react";

type Strategy = "killZone" | "ema" | "continuation" | "supplyDemand";
type Timeframe = "M1" | "M5" | "M10" | "M15" | "M30" | "H1" | "H4" | "D1";
type Direction = "BUY" | "SELL" | "BUY DEVELOPING" | "SELL DEVELOPING" | "WAITING" | "NO TRADE";
type ChartPoint = { x: number; y: number };
type ChartAnnotation = { type: "zone" | "entry" | "stopLoss" | "tp1" | "tp2" | "finalTp" | "retest" | "confirmation" | "structure"; label: string; price?: number | null; points?: ChartPoint[]; color?: "gold" | "green" | "red" | "white" };
type Projection = { available: boolean; setupType: string; zoneLow: number | null; zoneHigh: number | null; expectedEntry: number | null; expectedStopLoss: number | null; expectedTp1: number | null; expectedTp2: number | null; expectedFinalTp: number | null; retestRequired: boolean; retestStatus: string; confirmationRequired: string; confirmationStatus: string };
type TradeSignal = { direction: Direction; confidence: number; entry: number | null; stopLoss: number | null; risk: number | null; tp1: number | null; tp2: number | null; finalTp: number | null; invalidation: string };
type AnalysisResponse = { analysis?: string; tradeSignal?: TradeSignal; projection?: Projection; chartAnnotations?: ChartAnnotation[]; marketState?: string; setup?: string; confirmedConditions?: string[]; missingConditions?: string[]; aiCoach?: string; error?: string };
const timeframes: Timeframe[] = ["M1", "M5", "M10", "M15", "M30", "H1", "H4", "D1"];
function formatPrice(value: number | null | undefined) { if (value == null || !Number.isFinite(value)) return "WAIT"; return value.toLocaleString(undefined, { maximumFractionDigits: 5 }); }
function getSignalClass(direction: Direction) { if (direction === "BUY" || direction === "BUY DEVELOPING") return "signal-buy"; if (direction === "SELL" || direction === "SELL DEVELOPING") return "signal-sell"; return "signal-neutral"; }
function renderAnnotations(annotations: ChartAnnotation[]) { return annotations.map((a, i) => { const p = a.points ?? []; if (a.type === "zone" && p.length >= 2) { const xs = p.map(x => x.x), ys = p.map(x => x.y), minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys); return <div key={`z-${i}`} className="chart-zone-overlay" style={{ left: `${minX / 10}%`, top: `${minY / 10}%`, width: `${Math.max(2, (maxX - minX) / 10)}%`, height: `${Math.max(2, (maxY - minY) / 10)}%` }}><span>{a.label}</span></div>; } const point = p[0]; if (!point) return null; if (["entry", "stopLoss", "tp1", "tp2", "finalTp"].includes(a.type)) return <div key={`l-${i}`} className={`chart-level chart-level-${a.type}`} style={{ top: `${point.y / 10}%` }}><span>{a.label}</span>{a.price != null && <strong>{formatPrice(a.price)}</strong>}</div>; return <div key={`m-${i}`} className={`chart-marker chart-marker-${a.type}`} style={{ left: `${point.x / 10}%`, top: `${point.y / 10}%` }}><span>{a.label}</span></div>; }); }

export default function Home() {
  const [strategy, setStrategy] = useState<Strategy>("killZone");
  const [timeframe, setTimeframe] = useState<Timeframe>("M5");
  const [chart, setChart] = useState<string | null>(null);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [fileName, setFileName] = useState("");
  const [analysis, setAnalysis] = useState("");
  const [tradeSignal, setTradeSignal] = useState<TradeSignal | null>(null);
  const [projection, setProjection] = useState<Projection | null>(null);
  const [annotations, setAnnotations] = useState<ChartAnnotation[]>([]);
  const [marketState, setMarketState] = useState("");
  const [setup, setSetup] = useState("");
  const [confirmedConditions, setConfirmedConditions] = useState<string[]>([]);
  const [missingConditions, setMissingConditions] = useState<string[]>([]);
  const [aiCoach, setAiCoach] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  function clearResults() { setAnalysis(""); setTradeSignal(null); setProjection(null); setAnnotations([]); setMarketState(""); setSetup(""); setConfirmedConditions([]); setMissingConditions([]); setAiCoach(""); setError(""); }
  function changeStrategy(next: Strategy) { setStrategy(next); clearResults(); }
  function changeTimeframe(next: Timeframe) { setTimeframe(next); clearResults(); }
  function handleUpload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { setError("Please upload a chart image."); return; } setSelectedFile(file); setFileName(file.name); clearResults(); const reader = new FileReader(); reader.onload = () => setChart(reader.result as string); reader.readAsDataURL(file); }
  function clearChart() { setChart(null); setSelectedFile(null); setFileName(""); clearResults(); const input = document.getElementById("chart-upload") as HTMLInputElement | null; if (input) input.value = ""; }
  async function analyzeChart() { if (!selectedFile) { setError("Please upload a chart first."); return; } setLoading(true); clearResults(); try { const formData = new FormData(); formData.append("image", selectedFile); formData.append("strategy", strategy); formData.append("timeframe", timeframe); const response = await fetch("/api/analyze", { method: "POST", body: formData }); const data = (await response.json()) as AnalysisResponse; if (!response.ok) throw new Error(data.error || "Unable to analyze the chart."); setAnalysis(data.analysis ?? ""); setTradeSignal(data.tradeSignal ?? null); setProjection(data.projection ?? null); setAnnotations(data.chartAnnotations ?? []); setMarketState(data.marketState ?? ""); setSetup(data.setup ?? ""); setConfirmedConditions(data.confirmedConditions ?? []); setMissingConditions(data.missingConditions ?? []); setAiCoach(data.aiCoach ?? ""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to analyze the chart."); } finally { setLoading(false); } }
  async function askCoach(question: string) { if (!tradeSignal) return; setAiCoach("Analyzing your question..."); try { const response = await fetch("/api/coach", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question, strategy, timeframe, direction: tradeSignal.direction, confidence: tradeSignal.confidence, analysis, marketState, setup, confirmedConditions, missingConditions, tradeSignal, projection, chartAnnotations: annotations }) }); const data = (await response.json()) as { answer?: string; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to answer the question."); setAiCoach(data.answer || "The AI Coach could not establish an answer from the current result."); } catch (err) { setAiCoach(err instanceof Error ? err.message : "Unable to answer the AI Coach question."); } }

  const display = tradeSignal && (tradeSignal.direction === "BUY DEVELOPING" || tradeSignal.direction === "SELL DEVELOPING") && projection?.available ? { entry: projection.expectedEntry, stopLoss: projection.expectedStopLoss, risk: null, tp1: projection.expectedTp1, tp2: projection.expectedTp2, finalTp: projection.expectedFinalTp } : tradeSignal ? tradeSignal : null;
  const confirmed = tradeSignal?.direction === "BUY" || tradeSignal?.direction === "SELL";
  const developing = tradeSignal?.direction === "BUY DEVELOPING" || tradeSignal?.direction === "SELL DEVELOPING";

  return <main className="shell">
    <header className="header"><div className="brand-block"><img src="/vaulttrades-logo.png" alt="VaultTrades" className="logo" /><div className="tagline">Built by Traders.</div><div className="slogan">Focus, discipline, consistency.</div></div><div className="badge">ANALYZER</div></header>
    <div className="grid">
      <section className="card"><h2 className="title">Select Strategy</h2><p className="muted">Choose the independent strategy you want the chart analyzer to apply.</p>
        <button type="button" className={`strategy ${strategy === "killZone" ? "active" : ""}`} onClick={() => changeStrategy("killZone")}><strong>Killer Zone</strong><span className="muted">London liquidity sweep → MSS → FVG → entry</span></button>
        <button type="button" className={`strategy ${strategy === "ema" ? "active" : ""}`} onClick={() => changeStrategy("ema")}><strong>EMA</strong><span className="muted">EMA20 pullback → rejection → break → confirmation</span></button>
        <button type="button" className={`strategy ${strategy === "continuation" ? "active" : ""}`} onClick={() => changeStrategy("continuation")}><strong>Continuation</strong><span className="muted">Expansion → correction → structure → continuation</span></button>
        <button type="button" className={`strategy ${strategy === "supplyDemand" ? "active" : ""}`} onClick={() => changeStrategy("supplyDemand")}><strong>Supply &amp; Demand</strong><span className="muted">Zones → retest → reaction → confirmed entry</span></button>
      </section>
      <section className="card"><h2 className="title">Chart Analyzer</h2><p className="muted">Select your timeframe, upload your chart, then analyze.</p>
        <div className="timeframe-section"><div className="section-label">SELECT TIMEFRAME</div><div className="timeframe-grid">{timeframes.map(tf => <button key={tf} type="button" className={`timeframe-button ${timeframe === tf ? "selected" : ""}`} disabled={loading} aria-pressed={timeframe === tf} onClick={() => changeTimeframe(tf)}>{tf}</button>)}</div></div>
        <label className="upload" htmlFor="chart-upload"><input id="chart-upload" type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={handleUpload} />{!chart ? <><strong>Upload TradingView Chart</strong><div className="muted">PNG, JPG or WebP</div></> : <><strong>{fileName}</strong><div className="chart-wrapper"><img src={chart} alt="Uploaded trading chart" className="preview" />{annotations.length > 0 && <div className="chart-overlay">{renderAnnotations(annotations)}</div>}</div></>}</label>
        <div className="actions"><button type="button" className="primary" disabled={!selectedFile || loading} onClick={analyzeChart}>{loading ? "Analyzing Chart..." : "Analyze Chart"}</button><button type="button" className="secondary" onClick={clearChart} disabled={loading}>Clear</button></div>
        {error && <div className="error-box"><strong>Analysis Error</strong><p className="muted">{error}</p></div>}
      </section>
    </div>

    <section className="card execution-card"><div className="section-label">IMMEDIATE EXECUTION RESULT</div>{!tradeSignal ? <div style={{ marginTop: 12 }}><h2 className="title">Trade Signal</h2><p className="muted">Upload a chart and analyze it to receive the direct execution result.</p></div> : <div className={getSignalClass(tradeSignal.direction)} style={{ marginTop: 12, border: "1px solid #202b3a", borderRadius: 14, padding: 18 }}>
      <div className="execution-header"><div><div className="execution-label">EXECUTION STATE</div><div className="execution-direction">{tradeSignal.direction}</div></div><div className="confidence-box"><span>CONFIDENCE</span><strong>{tradeSignal.confidence}%</strong></div></div>
      <div className="execution-grid"><div className="execution-item"><span>ENTRY</span><strong>{formatPrice(display?.entry)}</strong></div><div className="execution-item"><span>STOP LOSS</span><strong>{formatPrice(display?.stopLoss)}</strong></div><div className="execution-item"><span>RISK</span><strong>{formatPrice(display?.risk)}</strong></div><div className="execution-item"><span>TP1</span><strong>{formatPrice(display?.tp1)}</strong></div><div className="execution-item"><span>TP2</span><strong>{formatPrice(display?.tp2)}</strong></div><div className="execution-item"><span>FINAL TP</span><strong>{formatPrice(display?.finalTp)}</strong></div></div>
      <div className="execution-status">{confirmed && <><span>EXECUTION:</span><strong>CONFIRMED</strong></>}{developing && <><span>EXECUTION:</span><strong>DEVELOPING — WAIT FOR CONFIRMATION</strong></>}{!confirmed && !developing && <><span>EXECUTION:</span><strong>NO CONFIRMED TRADE</strong></>}{projection?.retestRequired && <span>Retest: {projection.retestStatus}</span>}{projection?.confirmationStatus && <span>Confirmation: {projection.confirmationStatus}</span>}</div>
      {developing && projection?.confirmationRequired && <div className="execution-status"><span>REQUIRED NEXT:</span><strong>{projection.confirmationRequired}</strong></div>}
      {tradeSignal.invalidation && <div className="execution-status"><span>INVALIDATION:</span><strong>{tradeSignal.invalidation}</strong></div>}
    </div>}</section>

    {tradeSignal && <>
      <section className="card analysis-card"><h2 className="title">Market Map</h2><div className="market-map"><div><span className="muted">Current Market State</span><strong>{marketState || "Monitoring current market structure"}</strong></div><div><span className="muted">Current Setup</span><strong>{setup || "No completed setup has been reported yet."}</strong></div>{projection?.available && <div><span className="muted">Active / Expected Zone</span><strong>{formatPrice(projection.zoneLow)} — {formatPrice(projection.zoneHigh)}</strong></div>}<div><span className="muted">Confirmed Conditions</span><strong>{confirmedConditions.length ? confirmedConditions.join(" • ") : "No confirmed conditions reported yet"}</strong></div><div><span className="muted">What To Watch</span><strong>{missingConditions.length ? missingConditions.join(" • ") : "Continue monitoring the selected strategy conditions"}</strong></div></div></section>
      <section className="card analysis-card"><h2 className="title">Trade Roadmap</h2><div style={{ display: "grid", gap: 14, marginTop: 16 }}><div className="condition-box"><strong>Current Setup</strong><p style={{ whiteSpace: "pre-wrap", lineHeight: 1.7, marginBottom: 0 }}>{setup || "The selected strategy is monitoring the chart for its required sequence."}</p></div>{confirmedConditions.length > 0 && <div className="condition-box"><strong>What the Chart Has Confirmed</strong><ul>{confirmedConditions.map((c, i) => <li key={`c-${i}`}>{c}</li>)}</ul></div>}{missingConditions.length > 0 && <div className="condition-box"><strong>What the Chart Is Watching</strong><ul>{missingConditions.map((c, i) => <li key={`m-${i}`}>{c}</li>)}</ul></div>}</div></section>
      {analysis && <section className="card analysis-card"><h2 className="title">AI Trade Analysis</h2><p className="analysis-text">{analysis}</p></section>}
      <section className="card coach-card"><span className="muted">AI Coach</span><h2 className="title">Ask About This Setup</h2><p className="muted" style={{ lineHeight: 1.6 }}>AI Coach explains the selected strategy result. It does not create or change the trade signal or execution levels.</p><div className="coach-suggestions"><button type="button" onClick={() => void askCoach("Explain the current strategy result and why it is in this state.")}>Explain This Setup</button><button type="button" onClick={() => void askCoach("What condition is the selected strategy watching next?")}>What Am I Waiting For?</button><button type="button" onClick={() => void askCoach("What invalidates the current strategy idea?")}>What Invalidates It?</button></div><div className="coach-question"><input id="coach-question" type="text" placeholder="Ask the AI Coach a question..." onKeyDown={event => { if (event.key === "Enter") { const q = event.currentTarget.value.trim(); if (q) { void askCoach(q); event.currentTarget.value = ""; } } }} /><button type="button" className="primary" onClick={() => { const input = document.getElementById("coach-question") as HTMLInputElement | null; const q = input?.value.trim(); if (q) { void askCoach(q); if (input) input.value = ""; } }}>Ask</button></div>{aiCoach && <div className="coach-response"><span className="muted">AI Coach Response</span><p className="coach-response-text">{aiCoach}</p></div>}</section>
    </>}
    <footer className="footer"><div className="footer-brand">VAULTTRADES</div><div className="footer-disclaimer"><strong>Disclaimer:</strong> VaultTrades provides market analysis and educational information only. Trading involves substantial risk. Signals and analysis are not financial advice and should not be considered a guarantee of future results.</div><div className="footer-copy">© 2026 VaultTrades. All rights reserved.</div><div className="footer-developed">Built by Traders.</div></footer>
  </main>;
}
