import { ANALYZER_STRATEGY_MAP } from "../../../lib/strategies/analyzerProfiles";
import { getStrategyRules, type StrategyId } from "../../../lib/strategies";
import { analyzeAutoFibRetrace } from "../../../lib/strategies/autoFibRetrace";
import { evaluateTradeLifecycle, selectAllowedAbFibLevel } from "../../../lib/strategies/tradeLifecycle";
import { getTwelveDataTimeSeries } from "../../../lib/market-data/twelvedata";

export const runtime = "nodejs";
type Direction = "BUY" | "SELL" | "NO TRADE";
type EvidenceDirection = "BUY" | "SELL" | "NEUTRAL";
type MtfSnapshot = { timeframe:"M15"|"M5"; currentPrice:number|null; direction:EvidenceDirection; state:"CONFIRMATION"|"EXECUTION"|"NEUTRAL"; cycle:"BULLISH"|"BEARISH"|"NEUTRAL"; support:number|null; resistance:number|null; structureReason:string };
const finite=(v:unknown):v is number=>typeof v==="number"&&Number.isFinite(v);
const clean=(v:unknown)=>typeof v==="string"?v.trim():"";
function atr(c:Array<{high:number;low:number;close:number}>,n=14):number|null{if(c.length<n+1)return null;const tr:number[]=[];for(let i=0;i<c.length;i++){if(i===0)tr.push(c[i].high-c[i].low);else{const p=c[i-1],x=c[i];tr.push(Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close)))}}let a=tr.slice(0,n).reduce((x,y)=>x+y,0)/n;for(let i=n;i<tr.length;i++)a=(a*(n-1)+tr[i])/n;return a}
function volumeProfile(c:Array<{open:number;high:number;low:number;close:number;volume:number|null}>){const v=c.map(x=>x.volume).filter((x):x is number=>finite(x));if(v.length<21)return{currentVolume:null,averageVolume:null,ratio:null,expansion:false,candleDirection:"NEUTRAL",displacementATR:null};const currentVolume=v.at(-1)!;const base=v.slice(-21,-1);const averageVolume=base.reduce((a,b)=>a+b,0)/base.length;const ratio=averageVolume>0?currentVolume/averageVolume:null;const last=c.at(-1)!;const a=atr(c);return{currentVolume,averageVolume,ratio,expansion:ratio!==null&&ratio>=1.5,candleDirection:last.close>last.open?"BULLISH":last.close<last.open?"BEARISH":"NEUTRAL",displacementATR:a&&a>0?(last.high-last.low)/a:null}}
function inferMtfSnapshot(timeframe:"M15"|"M5",c:Array<{open:number;high:number;low:number;close:number}>):MtfSnapshot{const r=c.slice(-20),currentPrice=r.at(-1)?.close??null;if(!currentPrice||r.length<5)return{timeframe,currentPrice,direction:"NEUTRAL",state:timeframe==="M15"?"CONFIRMATION":"EXECUTION",cycle:"NEUTRAL",support:null,resistance:null,structureReason:"Insufficient independent timeframe evidence."};const highs=r.slice(0,-1).map(x=>x.high),lows=r.slice(0,-1).map(x=>x.low),support=lows.filter(x=>x<currentPrice).sort((a,b)=>b-a)[0]??null,resistance=highs.filter(x=>x>currentPrice).sort((a,b)=>a-b)[0]??null,first=r[0].close,last=r.at(-1)!;const directionalMove=(Math.max(...r.map(x=>x.high))-Math.min(...r.map(x=>x.low)))>0?(last.close-first)/(Math.max(...r.map(x=>x.high))-Math.min(...r.map(x=>x.low))):0;const bullish=last.close>first&&last.close>=last.open,bearish=last.close<first&&last.close<=last.open,direction:EvidenceDirection=bullish?"BUY":bearish?"SELL":"NEUTRAL";return{timeframe,currentPrice,direction,state:timeframe==="M15"?"CONFIRMATION":"EXECUTION",cycle:direction==="BUY"?"BULLISH":direction==="SELL"?"BEARISH":"NEUTRAL",support,resistance,structureReason:direction==="BUY"?`Independent ${timeframe} bullish structure; directional move ${(directionalMove*100).toFixed(1)}%.`:direction==="SELL"?`Independent ${timeframe} bearish structure; directional move ${(directionalMove*100).toFixed(1)}%.`:`Independent ${timeframe} structure is mixed/neutral.`}}
function math(direction:Direction,entry:number|null,stop:number|null,target:number|null,current:number|null){if(direction==="NO TRADE"||!finite(entry)||!finite(stop)||!finite(target))return{rr:null,valid:false,risk:null,reward:null,entryDistancePct:null,slDistancePct:null};const risk=direction==="BUY"?entry-stop:stop-entry,reward=direction==="BUY"?target-entry:entry-target,rr=risk>0?reward/risk:null,entryDistancePct=current&&current!==0?Math.abs(entry-current)/Math.abs(current)*100:null,slDistancePct=entry!==0?Math.abs(entry-stop)/Math.abs(entry)*100:null;return{rr,risk,reward,entryDistancePct,slDistancePct,valid:risk>0&&reward>0&&rr!==null&&rr>=2&&(slDistancePct===null||slDistancePct>=0.1)}}
function jsonText(raw:any):string{return raw.output?.flatMap((x:any)=>x.content??[]).filter((x:any)=>x.type==="output_text").map((x:any)=>x.text).join("").trim()||""}
export async function POST(request:Request){try{const body=await request.json();const strategyId=clean(body.strategy);const profile=ANALYZER_STRATEGY_MAP[strategyId];const candles=Array.isArray(body.candles)?body.candles.filter((c:any)=>finite(c?.open)&&finite(c?.high)&&finite(c?.low)&&finite(c?.close)):[];const currentPrice=finite(body.currentPrice)?body.currentPrice:candles.at(-1)?.close??null;if(!profile)return Response.json({error:"Invalid strategy selected."},{status:400});if(candles.length<30||!finite(currentPrice))return Response.json({error:"Not enough chart data for AI Scanner."},{status:422});const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return Response.json({error:"OpenAI API key is not configured."},{status:500});const prior=body.analysis??{},lifecycleInput=body.lifecycle??{},volume=volumeProfile(candles),sourceRules=profile.sourceIds.map((id:StrategyId)=>getStrategyRules(id)),selectedTimeframe=clean(prior?.market?.timeframe).toUpperCase(),mtfEnabled=["30M","1H","4H","1D","1W","1M"].includes(selectedTimeframe);let mtfEvidence:{enabled:boolean;htfTimeframe:string;m15:MtfSnapshot|null;m5:MtfSnapshot|null;relationship:string}={enabled:false,htfTimeframe:selectedTimeframe||"UNKNOWN",m15:null,m5:null,relationship:"MTF hierarchy is inactive below M30."};if(mtfEnabled){const symbol=clean(prior?.market?.asset);if(symbol){const[m15Market,m5Market]=await Promise.all([getTwelveDataTimeSeries({symbol,timeframe:"15m",outputsize:80}),getTwelveDataTimeSeries({symbol,timeframe:"5m",outputsize:80})]),m15=inferMtfSnapshot("M15",m15Market.candles),m5=inferMtfSnapshot("M5",m5Market.candles),htfDirection:Direction=prior?.projectedDirection==="BUY"||prior?.direction==="BUY"?"BUY":prior?.projectedDirection==="SELL"||prior?.direction==="SELL"?"SELL":"NO TRADE";mtfEvidence={enabled:true,htfTimeframe:selectedTimeframe,m15,m5,relationship:htfDirection!=="NO TRADE"&&m15.direction===htfDirection&&m5.direction===htfDirection?"M15 confirmation and M5 execution evidence align with the HTF direction.":htfDirection!=="NO TRADE"&&(m15.direction===htfDirection||m5.direction===htfDirection)?"One lower timeframe aligns with the HTF direction; the other is not fully aligned.":"Lower timeframe evidence does not currently align with the HTF direction."}}}
const sourceFib=strategyId==="fibRetracement"?analyzeAutoFibRetrace({candles:candles.map((c:any,i:number)=>({time:typeof c.time==="number"?c.time:Date.parse(c.datetime??"")||i,open:c.open,high:c.high,low:c.low,close:c.close,volume:finite(c.volume)?c.volume:undefined}))}):null;const fibBuyLevel=sourceFib?selectAllowedAbFibLevel(sourceFib.buy.fibLevels,"BUY",currentPrice):null,fibSellLevel=sourceFib?selectAllowedAbFibLevel(sourceFib.sell.fibLevels,"SELL",currentPrice):null;
const sourceFibContext=sourceFib?{state:sourceFib.state,confidence:sourceFib.confidence,buy:{ready:sourceFib.buy.ready,flipActive:sourceFib.buy.flipActive,fibLevels:sourceFib.buy.fibLevels.filter(x=>[82,78.6,68.1,61.8].includes(x.pct)),tp1:sourceFib.buy.tp1,tp2:sourceFib.buy.tp2,tp3:sourceFib.buy.tp3,tp4:sourceFib.buy.tp4},sell:{ready:sourceFib.sell.ready,flipActive:sourceFib.sell.flipActive,fibLevels:sourceFib.sell.fibLevels.filter(x=>[82,78.6,68.1,61.8].includes(x.pct)),tp1:sourceFib.sell.tp1,tp2:sourceFib.sell.tp2,tp3:sourceFib.sell.tp3,tp4:sourceFib.sell.tp4},projection:sourceFib.projection,orderBlocks:sourceFib.orderBlocks,confluence:{buy:sourceFib.buyConfluence,sell:sourceFib.sellConfluence}}:null;
const prompt=`You are the VaultTrades AI Scanner. The selected strategy/analyzer is the source of truth. Do not invent or replace its price levels.

HTF PROJECTED ENTRY LIFECYCLE — MANDATORY
For M30 and higher, a valid DEVELOPING HTF setup must expose its strategy-derived projected Entry, projected Stop Loss and projected TP1, TP2, TP3 and TP4/Final TP before confirmation. These are planning levels and must NOT require M15 or M5 confirmation. Never replace a source projection with current price. If the source analyzer provides a valid projected level, preserve it.

CONFIRMED ENTRY LIFECYCLE — MANDATORY
Actual/Confirmed Entry is separate from Projected Entry. It is established only when the existing HTF analyzer confirms the setup. Once established, it is fixed for that cycle. If the user runs analysis after confirmation and missed the moment of confirmation, report the state as BUY/SELL ACTIVE (or TP1 HIT where applicable), show the fixed Actual Entry and preserve the original projected Entry/SL/TP levels. Do not revert to WATCH merely because the confirmation happened in the past.

MTF HIERARCHY
For M30+: M15 = stronger confirmation evidence; M5 = execution confirmation evidence. M15/M5 affect probability/evidence only and never rewrite HTF Entry, SL or TP. Lower timeframe cycles are independent.

SELECTED STRATEGY\n${JSON.stringify({id:strategyId,name:profile.name,focus:profile.focus,rules:profile.rules,indicatorSpecs:profile.indicatorSpecs,sourceRules})}
EXISTING ANALYZER RESULT\n${JSON.stringify(prior)}
EXISTING TRADE LIFECYCLE INPUT\n${JSON.stringify(lifecycleInput)}
MTF EVIDENCE\n${JSON.stringify(mtfEvidence)}
CURRENT PRICE\n${currentPrice}
SOURCE FIB OUTPUT\n${JSON.stringify(sourceFibContext)}

AI REQUIREMENTS
1. Calculate probability from the available evidence; probability is not a guarantee.
2. If a valid developing strategy setup exists, populate projected Entry, SL and every available TP level in advance.
3. Never use current price or M5 price as HTF projected Entry.
4. Actual Entry is only the confirmed HTF entry and remains fixed.
5. If confirmation already occurred, describe the trade as BUY/SELL ACTIVE rather than WAIT and show Actual Entry.
6. Preserve projected levels after confirmation.
7. Do not alter the selected strategy calculations or lifecycle.
8. For FIB Retracement, projected Entry may only be 82.0%, 78.6%, 68.1% or 61.8% from the supplied source output.
Return JSON only.`;
const schema={type:"object",additionalProperties:false,properties:{projectedDirection:{type:"string",enum:["BUY","SELL","NO TRADE"]},analysisState:{type:"string",enum:["WATCH","ENTRY_ZONE","CONFIRMATION_PENDING","CONFIRMED","ACTIVE","TP1_HIT","INVALIDATED","TARGET_COMPLETE","CYCLE_COMPLETE"]},trend:{type:"string"},trendReason:{type:"string"},institutionalActivity:{type:"string",enum:["BULLISH","BEARISH","NEUTRAL","INSUFFICIENT"]},institutionalEvidence:{type:"array",items:{type:"string"}},confirmations:{type:"array",items:{type:"string"}},projectedProbability:{type:"number",minimum:0,maximum:100},entry:{type:["number","null"]},stopLoss:{type:["number","null"]},tp1:{type:["number","null"]},tp2:{type:["number","null"]},tp3:{type:["number","null"]},tp4:{type:["number","null"]},finalTp:{type:["number","null"]},confirmationPrice:{type:["number","null"]},reversalPrice:{type:["number","null"]},opposingLiquidityTarget:{type:["number","null"]},waitReason:{type:"string"},tradeReason:{type:"string"},invalidation:{type:"string"},pipeline:{type:"array",items:{type:"string"}},nextZone:{type:"string"}},required:["projectedDirection","analysisState","trend","trendReason","institutionalActivity","institutionalEvidence","confirmations","projectedProbability","entry","stopLoss","tp1","tp2","tp3","tp4","finalTp","confirmationPrice","reversalPrice","opposingLiquidityTarget","waitReason","tradeReason","invalidation","pipeline","nextZone"]};
const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:"gpt-4.1-mini",input:[{role:"user",content:[{type:"input_text",text:prompt}]}],max_output_tokens:4500,text:{format:{type:"json_schema",name:"vaulttrades_ai_scanner",strict:true,schema}}})});if(!response.ok)return Response.json({error:`AI Scanner request failed: ${(await response.text()).slice(0,300)}`},{status:502});const raw=await response.json(),text=jsonText(raw);if(!text)return Response.json({error:"AI Scanner returned no structured result."},{status:502});const ai=JSON.parse(text);
const direction:Direction=ai.projectedDirection==="BUY"||ai.projectedDirection==="SELL"?ai.projectedDirection:(prior.projectedDirection==="BUY"||prior.projectedDirection==="SELL"?prior.projectedDirection:prior.direction==="BUY"||prior.direction==="SELL"?prior.direction:"NO TRADE");
const sourceProjectedEntry=finite(prior.projectedEntry)?prior.projectedEntry:finite(prior.entry)?prior.entry:null;
const sourceProjectedStop=finite(prior.projectedStopLoss)?prior.projectedStopLoss:finite(prior.stopLoss)?prior.stopLoss:null;
const sourceProjectedTp1=finite(prior.projectedTp1)?prior.projectedTp1:finite(prior.tp1)?prior.tp1:null;
const sourceProjectedTp2=finite(prior.projectedTp2)?prior.projectedTp2:finite(prior.tp2)?prior.tp2:null;
const sourceProjectedTp3=finite(prior.projectedTp3)?prior.projectedTp3:finite(prior.tp3)?prior.tp3:null;
const sourceProjectedTp4=finite(prior.projectedTp4)?prior.projectedTp4:finite(prior.tp4)?prior.tp4:finite(prior.finalTp)?prior.finalTp:null;
const projectedEntry=strategyId==="fibRetracement"?(direction==="BUY"?fibBuyLevel?.price??sourceProjectedEntry:direction==="SELL"?fibSellLevel?.price??sourceProjectedEntry:sourceProjectedEntry):sourceProjectedEntry;
const projectedStopLoss=sourceProjectedStop??(finite(ai.stopLoss)?ai.stopLoss:null);
const projectedTp1=sourceProjectedTp1??(finite(ai.tp1)?ai.tp1:null),projectedTp2=sourceProjectedTp2??(finite(ai.tp2)?ai.tp2:null),projectedTp3=sourceProjectedTp3??(finite(ai.tp3)?ai.tp3:null),projectedTp4=sourceProjectedTp4??(finite(ai.tp4)?ai.tp4:finite(ai.finalTp)?ai.finalTp:null);
const priorActual=finite(prior.actualEntry)?prior.actualEntry:null,lifeActual=finite(lifecycleInput.actualEntry)?lifecycleInput.actualEntry:null;
const confirmedByAnalyzer=(prior?.decision==="TRADE"||prior?.confirmed===true||prior?.status==="CONFIRMED"||prior?.status==="ACTIVE")&&(prior?.direction===direction||prior?.projectedDirection===direction);
const actualEntry=lifeActual??priorActual??(confirmedByAnalyzer&&finite(prior.entry)?prior.entry:null);
const lifecycle=evaluateTradeLifecycle({direction:direction==="BUY"||direction==="SELL"?direction:"NONE",currentPrice,projectedEntry,actualEntry,projectedStopLoss,projectedTp1,projectedTp2,projectedFinalTp:projectedTp4,priorStatus:lifecycleInput.status??prior?.status??null,tp1AlreadyHit:lifecycleInput.tp1Hit===true||prior?.tp1Hit===true,stopAlreadyHit:lifecycleInput.stopHit===true||prior?.stopHit===true,cycleComplete:lifecycleInput.cycleComplete===true});
const active=actualEntry!==null&&(lifecycle.status==="ACTIVE"||lifecycle.status==="TP1_HIT"||confirmedByAnalyzer);const state=lifecycle.status==="TP1_HIT"?"TP1_HIT":lifecycle.status==="CYCLE_COMPLETE"?"CYCLE_COMPLETE":active?"ACTIVE":ai.analysisState;
const projectionTarget=direction==="BUY"?projectedTp4:direction==="SELL"?projectedTp4:projectedTp4;const projectionMath=math(direction,actualEntry??projectedEntry,projectedStopLoss,projectionTarget,currentPrice);
const statusMessage=active?`${direction} ACTIVE — confirmed entry ${actualEntry}. Projected entry ${projectedEntry??"—"} preserved.`:lifecycle.message;
return Response.json({...ai,projectedDirection:direction,analysisState:state,statusMessage,entry:projectedEntry,projectedEntry,actualEntry,stopLoss:projectedStopLoss,projectedStopLoss,tp1:projectedTp1,projectedTp1,tp2:projectedTp2,projectedTp2,tp3:projectedTp3,projectedTp3,tp4:projectedTp4,projectedTp4,finalTp:projectedTp4,projectedFinalTp:projectedTp4,confirmationPrice:actualEntry??ai.confirmationPrice,tp1Hit:lifecycle.tp1Hit,stopHit:lifecycle.stopHit,cycleStatus:lifecycle.status,sourceFib:sourceFibContext,fibEntryLevel:strategyId==="fibRetracement"?(direction==="BUY"?fibBuyLevel:fibSellLevel):null,allowedFibEntryPercentages:strategyId==="fibRetracement"?[82,78.6,68.1,61.8]:[],volumeProfile:volume,rr:projectionMath.rr,priceValidation:projectionMath,isExecutable:active&&projectionMath.valid,waitReason:active?statusMessage:ai.waitReason,tradeReason:active?statusMessage:ai.tradeReason,mtf:mtfEvidence,mtfHierarchy:{enabled:mtfEvidence.enabled,htfTimeframe:mtfEvidence.htfTimeframe,htfSourceOfTruth:true,m15Role:"STRONGER_CONFIRMATION",m5Role:"EXECUTION_CONFIRMATION",lowerTimeframesRewriteHtfLevels:false,projectedEntrySource:"HTF_STRATEGY",actualEntryRule:"HTF_CONFIRMED_ONLY",independentLowerTimeframeCycles:true}};
}catch(error){return Response.json({error:error instanceof Error?error.message:"AI Scanner failed."},{status:500})}}
