"use client";

import { useState } from "react";

export default function ReferralVaultClient({ locked, code, referralUrl, isAdmin, qualifiedCount = 0, currentRate = 8, totalEarned = 0, available = 0, pending = 0, adminReferrals = [] }: any) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(referralUrl); setCopied(true); setTimeout(() => setCopied(false), 1800); };

  if (locked) return <main style={{ minHeight: "100vh", background: "#050812", color: "#f4f6fb", display: "grid", placeItems: "center", padding: 24 }}><section style={{ maxWidth: 680, textAlign: "center", padding: 42, borderRadius: 20, background: "#0a0f1c", border: "1px solid rgba(212,166,55,.25)" }}><div style={{ color: "#d4a637", fontWeight: 800, letterSpacing: ".18em", fontSize: 12 }}>REFERRAL VAULT</div><h1 style={{ fontSize: 42, margin: "14px 0" }}>Referral Vault Locked</h1><p style={{ color: "#aeb5c6", lineHeight: 1.7 }}>Activate your first subscription to unlock your personal referral link and start earning up to 20% referral bonus.</p><a href="/subscription" style={{ display: "inline-block", marginTop: 22, padding: "14px 22px", borderRadius: 10, background: "#d4a637", color: "#050812", fontWeight: 800, textDecoration: "none" }}>Activate My Subscription</a></section></main>;

  const nextTarget = qualifiedCount < 16 ? 16 : qualifiedCount < 26 ? 26 : qualifiedCount < 51 ? 51 : qualifiedCount < 71 ? 71 : null;
  const nextRate = qualifiedCount < 16 ? 10 : qualifiedCount < 26 ? 12 : qualifiedCount < 51 ? 15 : qualifiedCount < 71 ? 20 : 20;
  const previousTarget = qualifiedCount < 16 ? 0 : qualifiedCount < 26 ? 16 : qualifiedCount < 51 ? 26 : qualifiedCount < 71 ? 51 : 71;
  const progress = nextTarget ? Math.min(100, Math.max(0, ((qualifiedCount - previousTarget) / (nextTarget - previousTarget)) * 100)) : 100;

  return <main style={{ minHeight: "100vh", background: "#050812", color: "#f4f6fb", padding: "42px 24px 80px" }}><div style={{ maxWidth: 1180, margin: "0 auto" }}>
    <div style={{ textAlign: "center", marginBottom: 34 }}><div style={{ color: "#d4a637", fontSize: 12, fontWeight: 800, letterSpacing: ".2em" }}>VAULTTRADES • REFERRAL VAULT</div><h1 style={{ fontSize: "clamp(36px,6vw,68px)", lineHeight: 1, margin: "14px 0" }}>EARN UP TO 20% REFERRAL BONUS</h1><p style={{ color: "#aeb5c6", maxWidth: 700, margin: "0 auto", lineHeight: 1.7 }}>Share your personal referral link, invite other traders, and earn commission when your referrals complete eligible subscription purchases.</p></div>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 14 }}><Metric title="Current Rate" value={isAdmin ? "Admin" : `${currentRate}%`} /><Metric title="Qualified Referrals" value={qualifiedCount} /><Metric title="Total Earned" value={`$${totalEarned.toFixed(2)}`} /></div>
    <section style={card}><div style={{ color: "#aeb5c6", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>YOUR REFERRAL LINK</div><div style={{ display: "flex", gap: 10, marginTop: 12, flexWrap: "wrap" }}><input readOnly value={referralUrl} style={{ flex: 1, minWidth: 250, padding: 13, borderRadius: 9, border: "1px solid rgba(255,255,255,.12)", background: "#050812", color: "#f4f6fb" }} /><button onClick={copy} style={button}>{copied ? "Copied" : "Copy Link"}</button><button onClick={() => navigator.share?.({ title: "VaultTrades", text: "Join VaultTrades", url: referralUrl })} style={secondary}>Share Link</button></div><div style={{ marginTop: 10, color: "#7f8799", fontSize: 12 }}>Referral code: {code}</div></section>
    <section style={card}><h2>How Referral Vault Works</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 12 }}>{[["01","SHARE","Share your personal Referral Vault link."],["02","JOIN","A new trader creates an account through your link."],["03","SUBSCRIBE","They complete an eligible paid subscription."],["04","EARN","Your commission is calculated server-side."]].map(([n,t,d]) => <div key={n} style={{ padding: 18, borderRadius: 12, background: "#050812", border: "1px solid rgba(255,255,255,.08)" }}><div style={{ color: "#d4a637", fontWeight: 900 }}>{n}</div><h3>{t}</h3><p style={{ color: "#aeb5c6", lineHeight: 1.5, fontSize: 13 }}>{d}</p></div>)}</div></section>
    {!isAdmin && <section style={card}><h2>Unlock Higher Referral Rewards</h2><div style={{ color: "#d7dbe7" }}>{qualifiedCount} qualified paid referrals {nextTarget ? `• ${nextTarget - qualifiedCount} more to reach ${nextRate}%` : "• Maximum rate reached"}</div><div style={{ height: 8, background: "#151b2a", borderRadius: 99, marginTop: 14, overflow: "hidden" }}><div style={{ width: `${progress}%`, height: "100%", background: "#d4a637" }} /></div><div style={{ display: "grid", gridTemplateColumns: "repeat(5,minmax(0,1fr))", gap: 8, marginTop: 18 }}>{[["Vault Core","0–15","8%"],["Vault Rise","16–25","10%"],["Vault Prime","26–50","12%"],["Vault Elite","51–70","15%"],["Vault Apex","71+","20%"]].map(([a,b,c]) => <div key={a} style={{ padding: 12, border: "1px solid rgba(255,255,255,.08)", borderRadius: 10 }}><b>{a}</b><div style={{ color: "#aeb5c6", fontSize: 12 }}>{b}</div><strong style={{ color: "#d4a637" }}>{c}</strong></div>)}</div></section>}
    <div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 14 }}><Metric title="Available Balance" value={`$${available.toFixed(2)}`} /><Metric title="Pending Commission" value={`$${pending.toFixed(2)}`} /><Metric title="Minimum Withdrawal" value="$50.00" /></div>
    {isAdmin && <section style={card}><h2>Admin Referral View</h2><p style={{ color: "#aeb5c6" }}>Admin commission rate is intentionally 0%. This view is for testing referral attribution and qualification without generating admin earnings.</p>{adminReferrals.length === 0 ? <p style={{ color: "#7f8799" }}>No referred users are currently attributed to this admin code.</p> : <div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th style={th}>Email</th><th style={th}>Status</th><th style={th}>Created</th></tr></thead><tbody>{adminReferrals.map((r: any) => <tr key={r.email}><td style={td}>{r.email}</td><td style={td}>{r.license_status || "inactive"}</td><td style={td}>{r.created_at ? new Date(r.created_at).toLocaleDateString() : "—"}</td></tr>)}</tbody></table></div>}</section>}
    <section style={card}><h2>Commission & Withdrawal Rules</h2><p style={{ color: "#aeb5c6", lineHeight: 1.7 }}>A click or registration does not create a qualified referral. A qualifying paid subscription is required. Commissions are calculated server-side in USD, may be reversed after refunds, and become withdrawable only when available balance reaches the $50 minimum.</p></section>
  </div></main>;
}
function Metric({ title, value }: { title: string; value: string | number }) { return <div style={{ padding: 22, borderRadius: 14, background: "#0a0f1c", border: "1px solid rgba(212,166,55,.18)" }}><div style={{ color: "#7f8799", fontSize: 12, fontWeight: 800 }}>{title}</div><div style={{ marginTop: 8, color: "#d4a637", fontSize: 30, fontWeight: 900 }}>{value}</div></div>; }
const card: any = { marginTop: 16, padding: 24, borderRadius: 14, background: "#0a0f1c", border: "1px solid rgba(212,166,55,.18)" };
const button: any = { padding: "13px 18px", border: 0, borderRadius: 9, background: "#d4a637", color: "#050812", fontWeight: 800, cursor: "pointer" };
const secondary: any = { padding: "13px 18px", borderRadius: 9, border: "1px solid rgba(212,166,55,.35)", background: "transparent", color: "#d7dbe7", fontWeight: 800, cursor: "pointer" };
const th: any = { textAlign: "left", padding: 12, color: "#7f8799", fontSize: 12 };
const td: any = { padding: 12, borderTop: "1px solid rgba(255,255,255,.07)", color: "#d7dbe7" };
